import {
  ServiceCategory,
  Cooperative,
  Worker,
  WorkerCertification,
  Customer,
  Booking,
  PaymentInvoice,
  RatingReview,
  WorkerWelfare,
  Grievance,
  DemandForecast,
  NotificationItem,
  UserProfile,
} from './database.types';

export const SEED_USERS: UserProfile[] = [
  {
    id: 'usr-cust-1',
    role: 'customer',
    name: 'Saumyadeep Sutradhar',
    email: 'saumyadeep.sutradhar@example.com',
    contact: '+91 98201 45678',
    language_preference: 'en',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    status: 'active',
    created_at: '2026-01-10T10:00:00Z',
  },
  {
    id: 'usr-work-1',
    role: 'worker',
    name: 'Rameshwar Patil',
    email: 'rameshwar.patil@sahyog.coop',
    contact: '+91 98199 87654',
    language_preference: 'mr',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    created_at: '2026-01-05T09:30:00Z',
  },
  {
    id: 'usr-work-2',
    role: 'worker',
    name: 'Sunita Devi',
    email: 'sunita.devi@sahyog.coop',
    contact: '+91 97112 34567',
    language_preference: 'hi',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    created_at: '2026-01-08T11:00:00Z',
  },
  {
    id: 'usr-admin-1',
    role: 'federation_admin',
    name: 'Balwant Singh Deshmukh',
    email: 'admin.mumbai@sahyog.coop',
    contact: '+91 94220 11223',
    language_preference: 'mr',
    avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    created_at: '2025-12-01T08:00:00Z',
  },
  {
    id: 'usr-super-1',
    role: 'super_admin',
    name: 'Dr. Arundhati Ghosh',
    email: 'superadmin@sahyog.gov.in',
    contact: '+91 98100 00001',
    language_preference: 'en',
    avatar_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    created_at: '2025-11-15T08:00:00Z',
  },
];

export const SEED_COOPERATIVES: Cooperative[] = [
  {
    id: 'coop-1',
    name: 'Mumbai Shramik Sahakari Sanstha Maryadit',
    registration_id: 'MSCS/MUM/2018/7421',
    region: 'Western Zone',
    city: 'Mumbai',
    state: 'Maharashtra',
    admin_contact: '+91 22 2568 9000',
    admin_email: 'mumbai.shramik@sahyog.coop',
    total_members: 4280,
    welfare_fund_pool: 6850000,
    established_year: 2018,
    verified_badge: true,
    logo_url: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=100&auto=format&fit=crop&q=80',
  },
  {
    id: 'coop-2',
    name: 'Delhi Karigar Kalyan Shramik Union',
    registration_id: 'DL/COOP/SOC/2019/3309',
    region: 'Northern Zone',
    city: 'New Delhi',
    state: 'Delhi NCR',
    admin_contact: '+91 11 2341 5566',
    admin_email: 'delhi.karigar@sahyog.coop',
    total_members: 3750,
    welfare_fund_pool: 5420000,
    established_year: 2019,
    verified_badge: true,
    logo_url: 'https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?w=100&auto=format&fit=crop&q=80',
  },
  {
    id: 'coop-3',
    name: 'Bengaluru Skilled Artisans Cooperative Society',
    registration_id: 'KA/BLR/COOP/2020/9102',
    region: 'Southern Zone',
    city: 'Bengaluru',
    state: 'Karnataka',
    admin_contact: '+91 80 4120 7890',
    admin_email: 'bengaluru.artisan@sahyog.coop',
    total_members: 3120,
    welfare_fund_pool: 4930000,
    established_year: 2020,
    verified_badge: true,
  },
  {
    id: 'coop-4',
    name: 'Pune Nirman & Seva Sahakari Society',
    registration_id: 'MH/PUNE/COOP/2021/4811',
    region: 'Western Zone',
    city: 'Pune',
    state: 'Maharashtra',
    admin_contact: '+91 20 2612 3444',
    admin_email: 'pune.nirman@sahyog.coop',
    total_members: 2450,
    welfare_fund_pool: 3810000,
    established_year: 2021,
    verified_badge: true,
  },
];

export const SEED_SERVICE_CATEGORIES: ServiceCategory[] = [
  {
    id: 'cat-1',
    slug: 'electricians',
    name: 'Electricians & Wiring',
    name_hi: 'इलेक्ट्रीशियन व वायरिंग',
    icon: 'Zap',
    description: 'Government-certified technicians for wiring, switchboards, MCB repair, inverter setup, and emergency short-circuits.',
    base_price_range: '₹249 - ₹699',
    popular_tasks: ['Short Circuit & Fuse Repair', 'Switchboard & Socket Installation', 'Inverter / UPS Setup', 'Ceiling Fan Installation', 'Full House Rewiring'],
    urgency_available: true,
    image_url: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'cat-2',
    slug: 'plumbers',
    name: 'Plumbers & Sanitation',
    name_hi: 'प्लम्बर व नलसाजी',
    icon: 'Wrench',
    description: 'Expert pipefitters for leakage fixes, tap/shower repair, water tank cleaning, sanitary installations, and emergency bursts.',
    base_price_range: '₹199 - ₹599',
    popular_tasks: ['Water Pipe Leakage Repair', 'Tap & Shower Replacement', 'Drain Unclogging', 'Water Tank Cleaning', 'Bathroom Sanitary Fitting'],
    urgency_available: true,
    image_url: 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'cat-3',
    slug: 'carpenters',
    name: 'Carpenters & Woodwork',
    name_hi: 'बढ़ई व काष्ठशिल्प',
    icon: 'Hammer',
    description: 'Skilled woodwork craftsmen for furniture repair, door/window hinges, lock replacements, modular kitchen fitting, and custom carpentry.',
    base_price_range: '₹299 - ₹899',
    popular_tasks: ['Door Lock & Hinge Repair', 'Furniture Assembly & Repair', 'Modular Kitchen Cabinet Fix', 'Custom Wood Shelves', 'Bed & Table Crafting'],
    urgency_available: false,
    image_url: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'cat-4',
    slug: 'painters',
    name: 'Painters & Wall Polishers',
    name_hi: 'पेंटर व पुताई कारीगर',
    icon: 'Paintbrush',
    description: 'Cooperative guild painters for interior/exterior emulsion, waterproof coating, wall putty, texture design, and touchups.',
    base_price_range: '₹499 - ₹1,499',
    popular_tasks: ['Single Room Fresh Coat', 'Waterproofing & Damp Repair', 'Wall Putty & Primer', 'Full Home Painting', 'Wood & Metal Enamel'],
    urgency_available: false,
    image_url: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'cat-5',
    slug: 'domestic-helpers',
    name: 'Domestic Helpers & Cooks',
    name_hi: 'घरेलू सहायक व रसोइया',
    icon: 'Utensils',
    description: 'Dignified, background-verified cooperative members for daily cooking, kitchen maintenance, dishwashing, and housekeeping support.',
    base_price_range: '₹299/day - ₹6,500/mo',
    popular_tasks: ['Healthy Home Cooking', 'Daily Kitchen Help', 'Vessel Cleaning & Sanitization', 'Event / Guest Meal Preparation', 'Part-time Deep Support'],
    urgency_available: true,
    image_url: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'cat-6',
    slug: 'caregivers',
    name: 'Elder & Patient Caregivers',
    name_hi: 'वरिष्ठ व रोगी देखभाल',
    icon: 'HeartHandshake',
    description: 'Compassionate, CPR & nursing-assisted certified attendants for elderly assistance, medication routine, mobility support, and post-surgery care.',
    base_price_range: '₹450/shift - ₹950/shift',
    popular_tasks: ['Elderly Daily Living Support', 'Post-Op Vital Monitoring', 'Mobility & Physical Exercise', 'Medication Reminders', 'Dementia Care Companionship'],
    urgency_available: true,
    image_url: 'https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'cat-7',
    slug: 'drivers',
    name: 'Verified Drivers & Chauffeurs',
    name_hi: 'प्रमाणित चालक (ड्राइवर)',
    icon: 'Car',
    description: 'Police-verified commercial & personal vehicle drivers for outstation trips, daily commute, night-duty relief, and airport transfers.',
    base_price_range: '₹349/trip - ₹799/day',
    popular_tasks: ['Outstation Round Trip', 'Daily City Chauffeur (8h)', 'Airport Drop & Pickup', 'Night Emergency Driver', 'Commercial Delivery Support'],
    urgency_available: true,
    image_url: 'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'cat-8',
    slug: 'gardeners',
    name: 'Gardeners & Landscapers',
    name_hi: 'माली व बागवानी विशेषज्ञ',
    icon: 'Trees',
    description: 'Eco-trained horticultural artisans for lawn pruning, terrace garden setup, organic composting, plant nourishment, and pest control.',
    base_price_range: '₹249 - ₹649',
    popular_tasks: ['Lawn Mowing & Hedge Trim', 'Terrace Garden Maintenance', 'Organic Pest Spray', 'Potting & Soil Reconditioning', 'Flowering Plant Care'],
    urgency_available: false,
    image_url: 'https://images.unsplash.com/photo-1592417817098-8f3d6eb22509?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'cat-9',
    slug: 'cleaners',
    name: 'Deep Cleaners & Sanitizers',
    name_hi: 'गहन सफाई व सैनिटाइजर',
    icon: 'Sparkles',
    description: 'Trained hygiene brigades for bathroom descaling, sofa/carpet shampooing, kitchen chimney degreasing, and full-home deep sanitization.',
    base_price_range: '₹399 - ₹1,899',
    popular_tasks: ['Intensive Bathroom Descaling', 'Sofa & Mattress Shampooing', 'Kitchen Chimney & Tile Degreasing', 'Full House Move-In Deep Clean', 'Balcony & Glass Scrubbing'],
    urgency_available: true,
    image_url: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'cat-10',
    slug: 'technicians',
    name: 'Appliance & AC Technicians',
    name_hi: 'उपकरण व एसी तकनीशियन',
    icon: 'Cpu',
    description: 'ITI-certified appliance mechanics for split/window AC servicing, refrigerator gas refill, washing machine repair, and microwave troubleshooting.',
    base_price_range: '₹299 - ₹899',
    popular_tasks: ['AC Foam Jet Deep Service', 'AC Gas Refill & Leak Fix', 'Washing Machine Drum & Motor Fix', 'Refrigerator Cooling Repair', 'RO Water Purifier Filter Change'],
    urgency_available: true,
    image_url: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=500&auto=format&fit=crop&q=80',
  },
];

export const SEED_WORKERS: Worker[] = [
  {
    id: 'wrk-1',
    user_id: 'usr-work-1',
    cooperative_id: 'coop-1',
    cooperative_name: 'Mumbai Shramik Sahakari Sanstha',
    full_name: 'Rameshwar Patil',
    skills: ['Certified Wireman', 'MCB Diagnostics', 'Industrial Inverter Setup', 'Home Automation', '3-Phase Power'],
    service_category_ids: ['cat-1', 'cat-10'],
    experience_years: 11,
    verification_status: 'verified',
    insurance_status: true,
    availability: 'online',
    rating: 4.95,
    total_ratings_count: 142,
    total_jobs_completed: 318,
    hourly_rate: 280,
    base_visit_fee: 150,
    location: {
      lat: 19.0760,
      lng: 72.8777,
      area: 'Dadar West',
      city: 'Mumbai',
    },
    police_verified: true,
    kyc_verified: true,
    bank_account_verified: true,
    bio: '11+ years of experience as an ITI-certified master electrician. Member of Mumbai Shramik Sahakari Sanstha since 2018. Committed to precision, zero safety compromises, and transparent fair billing.',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'wrk-2',
    user_id: 'usr-work-2',
    cooperative_id: 'coop-2',
    cooperative_name: 'Delhi Karigar Kalyan Shramik Union',
    full_name: 'Sunita Devi',
    skills: ['Elder Companion', 'Palliative Attendant', 'Medication Routine', 'Mobility Therapy', 'First Aid Certified'],
    service_category_ids: ['cat-6', 'cat-5'],
    experience_years: 8,
    verification_status: 'verified',
    insurance_status: true,
    availability: 'online',
    rating: 4.98,
    total_ratings_count: 189,
    total_jobs_completed: 412,
    hourly_rate: 320,
    base_visit_fee: 180,
    location: {
      lat: 28.6139,
      lng: 77.2090,
      area: 'Lajpat Nagar',
      city: 'New Delhi',
    },
    police_verified: true,
    kyc_verified: true,
    bank_account_verified: true,
    bio: 'Certified Healthcare Attendant with NSDC Level-4 credential. Warm, empathetic care for seniors with Parkinson, stroke recovery, and post-hospitalization rehabilitation.',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'wrk-3',
    user_id: 'usr-work-3',
    cooperative_id: 'coop-1',
    cooperative_name: 'Mumbai Shramik Sahakari Sanstha',
    full_name: 'Ganesh Shinde',
    skills: ['High Pressure Hydro Jetting', 'Concealed Pipe Leakage', 'RO System Repair', 'Geyser Installation', 'CPVC Jointing'],
    service_category_ids: ['cat-2'],
    experience_years: 9,
    verification_status: 'verified',
    insurance_status: true,
    availability: 'online',
    rating: 4.88,
    total_ratings_count: 98,
    total_jobs_completed: 245,
    hourly_rate: 250,
    base_visit_fee: 140,
    location: {
      lat: 19.1136,
      lng: 72.8697,
      area: 'Andheri East',
      city: 'Mumbai',
    },
    police_verified: true,
    kyc_verified: true,
    bank_account_verified: true,
    bio: 'Specialist in concealed wall leakages and emergency sewer blockages. All modern diagnostic equipment and ultrasonic pipe testers carried on-site.',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'wrk-4',
    user_id: 'usr-work-4',
    cooperative_id: 'coop-3',
    cooperative_name: 'Bengaluru Skilled Artisans Cooperative Society',
    full_name: 'Manjunath Reddy',
    skills: ['Hardwood Joinery', 'Hydraulic Hinges', 'Modular Kitchens', 'Antique Restoration', 'Custom Bookcases'],
    service_category_ids: ['cat-3'],
    experience_years: 14,
    verification_status: 'verified',
    insurance_status: true,
    availability: 'busy',
    rating: 4.92,
    total_ratings_count: 165,
    total_jobs_completed: 390,
    hourly_rate: 340,
    base_visit_fee: 200,
    location: {
      lat: 12.9716,
      lng: 77.5946,
      area: 'Indiranagar',
      city: 'Bengaluru',
    },
    police_verified: true,
    kyc_verified: true,
    bank_account_verified: true,
    bio: 'Master Craftsman in Teak and Sheesham woodwork. 14 years dedicated to fine carpentry and modular installations with zero defect tolerance.',
    avatar_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'wrk-5',
    user_id: 'usr-work-5',
    cooperative_id: 'coop-4',
    cooperative_name: 'Pune Nirman & Seva Sahakari Society',
    full_name: 'Pooja Kadam',
    skills: ['Industrial Deep Scrubbing', 'Hospital Grade Sanitization', 'Sofa Upholstery Extraction', 'Kitchen Chimney Restoration'],
    service_category_ids: ['cat-9'],
    experience_years: 6,
    verification_status: 'verified',
    insurance_status: true,
    availability: 'online',
    rating: 4.91,
    total_ratings_count: 114,
    total_jobs_completed: 280,
    hourly_rate: 260,
    base_visit_fee: 150,
    location: {
      lat: 18.5204,
      lng: 73.8567,
      area: 'Kothrud',
      city: 'Pune',
    },
    police_verified: true,
    kyc_verified: true,
    bank_account_verified: true,
    bio: 'Leader of the Pune Sahakari Women Clean Hygiene Brigade. Eco-friendly biodegradable agents and high-temp steam sterilizers used.',
    avatar_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'wrk-6',
    user_id: 'usr-work-6',
    cooperative_id: 'coop-2',
    cooperative_name: 'Delhi Karigar Kalyan Shramik Union',
    full_name: 'Mohammad Irfan',
    skills: ['Inverter Split AC Expert', 'Ductless Multi-zone', 'PCB Chip Repair', 'Compressor Overhaul', 'Ecofriendly Gas Recharging'],
    service_category_ids: ['cat-10', 'cat-1'],
    experience_years: 10,
    verification_status: 'verified',
    insurance_status: true,
    availability: 'online',
    rating: 4.87,
    total_ratings_count: 87,
    total_jobs_completed: 215,
    hourly_rate: 290,
    base_visit_fee: 160,
    location: {
      lat: 28.5355,
      lng: 77.2600,
      area: 'Okhla Phase 3',
      city: 'New Delhi',
    },
    police_verified: true,
    kyc_verified: true,
    bank_account_verified: true,
    bio: 'Certified Refrigeration & Air Conditioning mechanic with 10 years experience. Fast diagnostics and guaranteed 60-day cooperative warranty on repairs.',
    avatar_url: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'wrk-7',
    user_id: 'usr-work-7',
    cooperative_id: 'coop-1',
    cooperative_name: 'Mumbai Shramik Sahakari Sanstha',
    full_name: 'Subhash Yadav',
    skills: ['Commercial Heavy Duty', 'VIP Defensive Driving', 'Highway Navigation', 'Automatic & Manual Fleet'],
    service_category_ids: ['cat-7'],
    experience_years: 12,
    verification_status: 'verified',
    insurance_status: true,
    availability: 'online',
    rating: 4.96,
    total_ratings_count: 178,
    total_jobs_completed: 530,
    hourly_rate: 220,
    base_visit_fee: 150,
    location: {
      lat: 19.0178,
      lng: 72.8478,
      area: 'Worli',
      city: 'Mumbai',
    },
    police_verified: true,
    kyc_verified: true,
    bank_account_verified: true,
    bio: 'Professional driver with clean 12-year incident-free record. Proficient in city navigation, outstation travel, and luxury vehicles.',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'wrk-8',
    user_id: 'usr-work-8',
    cooperative_id: 'coop-3',
    cooperative_name: 'Bengaluru Skilled Artisans Cooperative Society',
    full_name: 'Anand Kumar',
    skills: ['Terrace Garden Setup', 'Lawn Landscaping', 'Soil Microbiology', 'Rare Bonsai Grafting', 'Drip Irrigation'],
    service_category_ids: ['cat-8'],
    experience_years: 7,
    verification_status: 'verified',
    insurance_status: true,
    availability: 'online',
    rating: 4.94,
    total_ratings_count: 92,
    total_jobs_completed: 180,
    hourly_rate: 240,
    base_visit_fee: 120,
    location: {
      lat: 12.9279,
      lng: 77.6271,
      area: 'Koramangala',
      city: 'Bengaluru',
    },
    police_verified: true,
    kyc_verified: true,
    bank_account_verified: true,
    bio: 'Graduate in Agricultural Horticulture. Passionate about reviving urban balcony biodiversity and organic vegetable patches.',
    avatar_url: 'https://images.unsplash.com/photo-1592417817098-8f3d6eb22513?w=500&auto=format&fit=crop&q=80',
  },
];

export const SEED_CERTIFICATIONS: WorkerCertification[] = [
  {
    id: 'cert-1',
    worker_id: 'wrk-1',
    certificate_name: 'National Skill Qualification Framework (NSQF) Level-5 Electrician',
    issuing_body: 'National Skill Development Corporation (NSDC) & Ministry of Skill Development',
    file_url: 'https://images.unsplash.com/photo-1589330694653-ded6df03f754?w=600&auto=format&fit=crop&q=80',
    verified: true,
    issue_date: '2021-04-15',
    expiry_date: '2031-04-14',
  },
  {
    id: 'cert-2',
    worker_id: 'wrk-1',
    certificate_name: 'Maharashtra PWD Class-A Electrical Wireman License',
    issuing_body: 'Licensing Board, Industries, Energy and Labour Dept, Govt of Maharashtra',
    file_url: 'https://images.unsplash.com/photo-1589330694653-ded6df03f754?w=600&auto=format&fit=crop&q=80',
    verified: true,
    issue_date: '2019-06-10',
    expiry_date: '2029-06-09',
  },
  {
    id: 'cert-3',
    worker_id: 'wrk-2',
    certificate_name: 'Geriatric Attendant & CPR First-Aid Certified Provider',
    issuing_body: 'Healthcare Sector Skill Council (HSSC)',
    file_url: 'https://images.unsplash.com/photo-1589330694653-ded6df03f754?w=600&auto=format&fit=crop&q=80',
    verified: true,
    issue_date: '2022-02-18',
    expiry_date: '2027-02-17',
  },
  {
    id: 'cert-4',
    worker_id: 'wrk-3',
    certificate_name: 'Master Plumber Certification (Plumbing Skill Council)',
    issuing_body: 'Indian Plumbing Skills Council (IPSC)',
    file_url: 'https://images.unsplash.com/photo-1589330694653-ded6df03f754?w=600&auto=format&fit=crop&q=80',
    verified: true,
    issue_date: '2020-08-01',
    expiry_date: '2030-07-31',
  },
];

export const SEED_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    user_id: 'usr-cust-1',
    full_name: 'Saumyadeep Sutradhar',
    contact: '+91 98201 45678',
    addresses: [
      {
        id: 'addr-1',
        label: 'Home (Bandra West)',
        address_line: 'Flat 402, Sea Crest Apartments, Perry Cross Road, Bandra West',
        city: 'Mumbai',
        pincode: '400050',
        lat: 19.0596,
        lng: 72.8295,
      },
      {
        id: 'addr-2',
        label: 'Parents House (Dadar)',
        address_line: '12 Shivaji Park, Keluskar Road, Dadar West',
        city: 'Mumbai',
        pincode: '400028',
        lat: 19.0280,
        lng: 72.8385,
      },
    ],
    is_institution: false,
  },
];

export const SEED_BOOKINGS: Booking[] = [
  {
    id: 'bk-101',
    booking_code: 'SHY-2026-9041',
    customer_id: 'cust-1',
    customer_name: 'Saumyadeep Sutradhar',
    customer_contact: '+91 98201 45678',
    worker_id: 'wrk-1',
    worker_name: 'Rameshwar Patil',
    worker_contact: '+91 98199 87654',
    worker_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    cooperative_name: 'Mumbai Shramik Sahakari Sanstha',
    service_category_id: 'cat-1',
    service_category_name: 'Electricians & Wiring',
    service_task: 'Inverter / UPS Backup Setup and MCB Diagnostics',
    description: 'Frequent tripping in master bedroom and need to connect 1.5 kVA inverter correctly to load circuit.',
    status: 'in_progress',
    scheduled_time: '2026-08-26T10:30:00+05:30',
    is_emergency: false,
    location: {
      address: 'Flat 402, Sea Crest Apartments, Perry Cross Road, Bandra West, Mumbai 400050',
      lat: 19.0596,
      lng: 72.8295,
    },
    price_breakdown: {
      worker_wage: 650,
      welfare_contribution: 50,
      coop_admin_fee: 40,
      platform_fee: 0,
      tax_amount: 0,
      emergency_fee: 0,
      total_amount: 740,
    },
    notes: 'Worker carrying calibrated multimeters and insulated screwdrivers. Identity badge verified.',
    created_at: '2026-08-25T18:30:00Z',
  },
  {
    id: 'bk-102',
    booking_code: 'SHY-2026-8812',
    customer_id: 'cust-1',
    customer_name: 'Saumyadeep Sutradhar',
    customer_contact: '+91 98201 45678',
    worker_id: 'wrk-3',
    worker_name: 'Ganesh Shinde',
    worker_contact: '+91 98223 99881',
    worker_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    cooperative_name: 'Mumbai Shramik Sahakari Sanstha',
    service_category_id: 'cat-2',
    service_category_name: 'Plumbers & Sanitation',
    service_task: 'Emergency Bathroom Pipe Leakage & Tap Seal',
    description: 'Under-sink hot water pipe leaking rapidly into cabinet.',
    status: 'completed',
    scheduled_time: '2026-08-20T14:00:00+05:30',
    is_emergency: true,
    location: {
      address: 'Flat 402, Sea Crest Apartments, Perry Cross Road, Bandra West, Mumbai 400050',
      lat: 19.0596,
      lng: 72.8295,
    },
    price_breakdown: {
      worker_wage: 520,
      welfare_contribution: 45,
      coop_admin_fee: 35,
      platform_fee: 0,
      tax_amount: 0,
      emergency_fee: 100,
      total_amount: 700,
    },
    notes: 'Urgent leak addressed in 25 minutes. New brass connector fitted.',
    created_at: '2026-08-20T13:10:00Z',
  },
];

export const SEED_INVOICES: PaymentInvoice[] = [
  {
    id: 'inv-101',
    booking_id: 'bk-102',
    booking_code: 'SHY-2026-8812',
    customer_name: 'Saumyadeep Sutradhar',
    worker_name: 'Ganesh Shinde',
    cooperative_name: 'Mumbai Shramik Sahakari Sanstha',
    amount: 700,
    payment_status: 'completed',
    payment_method: 'UPI',
    gateway_reference: 'UPI/MUM/20260820/9982410',
    invoice_number: 'COOP-INV-2026-08812',
    created_at: '2026-08-20T14:45:00Z',
  },
];

export const SEED_RATINGS: RatingReview[] = [
  {
    id: 'rev-1',
    booking_id: 'bk-102',
    rated_by: 'usr-cust-1',
    rated_by_name: 'Saumyadeep Sutradhar',
    rated_user_id: 'usr-work-3',
    rating: 5,
    comment: 'Exceptional service! Ganesh arrived within 20 mins during an emergency leak. Fixed it cleanly with authentic parts and explained the fair cooperative cost breakdown.',
    tags: ['Punctual', 'Expert Work', 'Fair Transparent Pricing', 'Cooperative Pride'],
    created_at: '2026-08-20T15:30:00Z',
  },
  {
    id: 'rev-2',
    booking_id: 'bk-100',
    rated_by: 'usr-cust-2',
    rated_by_name: 'Rajesh Nair',
    rated_user_id: 'usr-work-1',
    rating: 5,
    comment: 'Rameshwar is a master electrician. Rewired our complete living room switchboard and tested all surge protectors. Knowing 100% of my money goes to him and the welfare fund makes me proud to choose SAHYOG over corporate apps.',
    tags: ['Master Craft', 'Safety First', 'Respectful'],
    created_at: '2026-08-18T16:00:00Z',
  },
];

export const SEED_WELFARE: WorkerWelfare[] = [
  {
    id: 'welf-1',
    worker_id: 'wrk-1',
    worker_name: 'Rameshwar Patil',
    insurance_provider: 'Ayushman Bharat PM-JAY & United India Group Accidental Shield',
    policy_number: 'AB-PMJAY-MH-8842109',
    coverage_amount: 500000,
    expiry_date: '2027-03-31',
    welfare_fund_contribution: 14850,
    cooperative_dividend_earned: 4200,
    emergency_claim_status: 'none',
  },
  {
    id: 'welf-2',
    worker_id: 'wrk-2',
    worker_name: 'Sunita Devi',
    insurance_provider: 'National Health Insurance Guild + Delhi Cooperative Mutual Cover',
    policy_number: 'DL-COOP-HEALTH-3199',
    coverage_amount: 500000,
    expiry_date: '2027-04-30',
    welfare_fund_contribution: 18400,
    cooperative_dividend_earned: 5600,
    emergency_claim_status: 'none',
  },
];

export const SEED_GRIEVANCES: Grievance[] = [
  {
    id: 'grv-1',
    ticket_number: 'GRV-2026-0042',
    filed_by_role: 'worker',
    filed_by_id: 'usr-work-1',
    filed_by_name: 'Rameshwar Patil',
    category: 'welfare_delay',
    description: 'Annual tool maintenance subsidy of ₹2,500 pending verification by zone auditor.',
    status: 'under_review',
    resolution_notes: 'Federation Admin verified tool receipt. Payout scheduled for upcoming Friday ledger batch.',
    assigned_admin_name: 'Balwant Singh Deshmukh',
    created_at: '2026-08-22T10:00:00Z',
  },
  {
    id: 'grv-2',
    ticket_number: 'GRV-2026-0039',
    filed_by_role: 'customer',
    filed_by_id: 'usr-cust-1',
    filed_by_name: 'Saumyadeep Sutradhar',
    category: 'quality_of_work',
    description: 'Minor clarification on sealant drying time for bathroom tile joint.',
    status: 'resolved',
    resolution_notes: 'Worker called customer and provided 24-hr curing instructions. Resolved satisfactorily.',
    assigned_admin_name: 'Balwant Singh Deshmukh',
    created_at: '2026-08-21T09:00:00Z',
  },
];

export const SEED_DEMAND_FORECASTS: DemandForecast[] = [
  {
    id: 'df-1',
    region: 'Mumbai Western Suburbs (Bandra - Andheri)',
    city: 'Mumbai',
    service_category_id: 'cat-1',
    service_category_name: 'Electricians & Wiring',
    predicted_demand_units: 480,
    active_workers_available: 390,
    deficit_or_surplus: -90,
    period: 'Upcoming Week',
    confidence_score: 0.94,
    ai_recommendation: 'Predicted 23% spike due to monsoon load surges. Recommend activating 15 reserve apprentice wiremen from Thane society.',
    generated_at: '2026-08-25T06:00:00Z',
  },
  {
    id: 'df-2',
    region: 'Delhi NCR (South & Central)',
    city: 'New Delhi',
    service_category_id: 'cat-6',
    service_category_name: 'Elder & Patient Caregivers',
    predicted_demand_units: 320,
    active_workers_available: 345,
    deficit_or_surplus: 25,
    period: 'Next Month',
    confidence_score: 0.91,
    ai_recommendation: 'Adequate balance. Consider conducting specialized dementia companion refresher workshop for surplus pool.',
    generated_at: '2026-08-25T06:00:00Z',
  },
  {
    id: 'df-3',
    region: 'Bengaluru Tech Corridor (Koramangala - Whitefield)',
    city: 'Bengaluru',
    service_category_id: 'cat-9',
    service_category_name: 'Deep Cleaners & Sanitizers',
    predicted_demand_units: 610,
    active_workers_available: 480,
    deficit_or_surplus: -130,
    period: 'Upcoming Week',
    confidence_score: 0.96,
    ai_recommendation: 'High festive move-in demand. Reallocate 25 hygiene brigade teams from North Bengaluru cluster with temporary travel stipend.',
    generated_at: '2026-08-25T06:00:00Z',
  },
  {
    id: 'df-4',
    region: 'Pune Central & Kothrud',
    city: 'Pune',
    service_category_id: 'cat-10',
    service_category_name: 'Appliance & AC Technicians',
    predicted_demand_units: 290,
    active_workers_available: 285,
    deficit_or_surplus: -5,
    period: 'Seasonal Spike',
    confidence_score: 0.89,
    ai_recommendation: 'Stable capacity. Pre-book gas canister inventories with wholesale cooperative supplier.',
    generated_at: '2026-08-25T06:00:00Z',
  },
];

export const SEED_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    user_id: 'usr-cust-1',
    title: 'Artisan En Route',
    message: 'Rameshwar Patil (Mumbai Shramik Sahakari) is en route to your Bandra address. Estimated arrival: 10:25 AM.',
    type: 'booking',
    read_status: false,
    created_at: '2026-08-26T00:50:00Z',
  },
  {
    id: 'notif-2',
    user_id: 'usr-work-1',
    title: 'Welfare Dividend Credited',
    message: 'Cooperative annual surplus dividend of ₹4,200 has been credited to your welfare mutual fund account.',
    type: 'welfare',
    read_status: false,
    created_at: '2026-08-25T12:00:00Z',
  },
  {
    id: 'notif-3',
    user_id: 'usr-admin-1',
    title: '3 New Member KYC Applications',
    message: 'Review pending trade certifications and police verifications for Dadar Zone plumbers.',
    type: 'verification',
    read_status: false,
    created_at: '2026-08-25T14:30:00Z',
  },
];
