import {
  ServiceCategory,
  Cooperative,
  Worker,
  WorkerCertification,
  Customer,
  Booking,
  PaymentInvoice,
  RatingReview,
  WorkerWelfare,
  Grievance,
  DemandForecast,
  NotificationItem,
  UserProfile,
} from './database.types';

export const SEED_USERS: UserProfile[] = [
  {
    id: 'usr-cust-1',
    role: 'customer',
    name: 'Saumyadeep Sutradhar',
    email: 'saumyadeep.sutradhar@example.com',
    contact: '+91 98201 45678',
    language_preference: 'en',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    status: 'active',
    created_at: '2026-01-10T10:00:00Z',
  },
  {
    id: 'usr-work-1',
    role: 'worker',
    name: 'Rameshwar Patil',
    email: 'rameshwar.patil@sahyog.coop',
    contact: '+91 98199 87654',
    language_preference: 'mr',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    created_at: '2026-01-05T09:30:00Z',
  },
  {
    id: 'usr-work-2',
    role: 'worker',
    name: 'Sunita Devi',
    email: 'sunita.devi@sahyog.coop',
    contact: '+91 97112 34567',
    language_preference: 'hi',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    created_at: '2026-01-08T11:00:00Z',
  },
  {
    id: 'usr-admin-1',
    role: 'federation_admin',
    name: 'Balwant Singh Deshmukh',
    email: 'admin.mumbai@sahyog.coop',
    contact: '+91 94220 11223',
    language_preference: 'mr',
    avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    created_at: '2025-12-01T08:00:00Z',
  },
  {
    id: 'usr-super-1',
    role: 'super_admin',
    name: 'Dr. Arundhati Ghosh',
    email: 'superadmin@sahyog.gov.in',
    contact: '+91 98100 00001',
    language_preference: 'en',
    avatar_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    created_at: '2025-11-15T08:00:00Z',
  },
];

export const SEED_COOPERATIVES: Cooperative[] = [
  {
    id: 'coop-1',
    name: 'Mumbai Shramik Sahakari Sanstha Maryadit',
    registration_id: 'MSCS/MUM/2018/7421',
    region: 'Western Zone',
    city: 'Mumbai',
    state: 'Maharashtra',
    admin_contact: '+91 22 2568 9000',
    admin_email: 'mumbai.shramik@sahyog.coop',
    total_members: 4280,
    welfare_fund_pool: 6850000,
    established_year: 2018,
    verified_badge: true,
    logo_url: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=100&auto=format&fit=crop&q=80',
  },
  {
    id: 'coop-2',
    name: 'Delhi Karigar Kalyan Shramik Union',
    registration_id: 'DL/COOP/SOC/2019/3309',
    region: 'Northern Zone',
    city: 'New Delhi',
    state: 'Delhi NCR',
    admin_contact: '+91 11 2341 5566',
    admin_email: 'delhi.karigar@sahyog.coop',
    total_members: 3750,
    welfare_fund_pool: 5420000,
    established_year: 2019,
    verified_badge: true,
    logo_url: 'https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?w=100&auto=format&fit=crop&q=80',
  },
  {
    id: 'coop-3',
    name: 'Bengaluru Skilled Artisans Cooperative Society',
    registration_id: 'KA/BLR/COOP/2020/9102',
    region: 'Southern Zone',
    city: 'Bengaluru',
    state: 'Karnataka',
    admin_contact: '+91 80 4120 7890',
    admin_email: 'bengaluru.artisan@sahyog.coop',
    total_members: 3120,
    welfare_fund_pool: 4930000,
    established_year: 2020,
    verified_badge: true,
  },
  {
    id: 'coop-4',
    name: 'Pune Nirman & Seva Sahakari Society',
    registration_id: 'MH/PUNE/COOP/2021/4811',
    region: 'Western Zone',
    city: 'Pune',
    state: 'Maharashtra',
    admin_contact: '+91 20 2612 3444',
    admin_email: 'pune.nirman@sahyog.coop',
    total_members: 2450,
    welfare_fund_pool: 3810000,
    established_year: 2021,
    verified_badge: true,
  },
];

export const SEED_SERVICE_CATEGORIES: ServiceCategory[] = [
  {
    id: 'cat-1',
    slug: 'electricians',
    name: 'Electricians & Wiring',
    name_hi: 'इलेक्ट्रीशियन व वायरिंग',
    icon: 'Zap',
    description: 'Government-certified technicians for wiring, switchboards, MCB repair, inverter setup, and emergency short-circuits.',
    base_price_range: '₹249 - ₹699',
    popular_tasks: ['Short Circuit & Fuse Repair', 'Switchboard & Socket Installation', 'Inverter / UPS Setup', 'Ceiling Fan Installation', 'Full House Rewiring'],
    urgency_available: true,
    image_url: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'cat-2',
    slug: 'plumbers',
    name: 'Plumbers & Sanitation',
    name_hi: 'प्लम्बर व नलसाजी',
    icon: 'Wrench',
    description: 'Expert pipefitters for leakage fixes, tap/shower repair, water tank cleaning, sanitary installations, and emergency bursts.',
    base_price_range: '₹199 - ₹599',
    popular_tasks: ['Water Pipe Leakage Repair', 'Tap & Shower Replacement', 'Drain Unclogging', 'Water Tank Cleaning', 'Bathroom Sanitary Fitting'],
    urgency_available: true,
    image_url: 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'cat-3',
    slug: 'carpenters',
    name: 'Carpenters & Woodwork',
    name_hi: 'बढ़ई व काष्ठशिल्प',
    icon: 'Hammer',
    description: 'Skilled woodwork craftsmen for furniture repair, door/window hinges, lock replacements, modular kitchen fitting, and custom carpentry.',
    base_price_range: '₹299 - ₹899',
    popular_tasks: ['Door Lock & Hinge Repair', 'Furniture Assembly & Repair', 'Modular Kitchen Cabinet Fix', 'Custom Wood Shelves', 'Bed & Table Crafting'],
    urgency_available: false,
    image_url: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'cat-4',
    slug: 'painters',
    name: 'Painters & Wall Polishers',
    name_hi: 'पेंटर व पुताई कारीगर',
    icon: 'Paintbrush',
    description: 'Cooperative guild painters for interior/exterior emulsion, waterproof coating, wall putty, texture design, and touchups.',
    base_price_range: '₹499 - ₹1,499',
    popular_tasks: ['Single Room Fresh Coat', 'Waterproofing & Damp Repair', 'Wall Putty & Primer', 'Full Home Painting', 'Wood & Metal Enamel'],
    urgency_available: false,
    image_url: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'cat-5',
    slug: 'domestic-helpers',
    name: 'Domestic Helpers & Cooks',
    name_hi: 'घरेलू सहायक व रसोइया',
    icon: 'Utensils',
    description: 'Dignified, background-verified cooperative members for daily cooking, kitchen maintenance, dishwashing, and housekeeping support.',
    base_price_range: '₹299/day - ₹6,500/mo',
    popular_tasks: ['Healthy Home Cooking', 'Daily Kitchen Help', 'Vessel Cleaning & Sanitization', 'Event / Guest Meal Preparation', 'Part-time Deep Support'],
    urgency_available: true,
    image_url: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'cat-6',
    slug: 'caregivers',
    name: 'Elder & Patient Caregivers',
    name_hi: 'वरिष्ठ व रोगी देखभाल',
    icon: 'HeartHandshake',
    description: 'Compassionate, CPR & nursing-assisted certified attendants for elderly assistance, medication routine, mobility support, and post-surgery care.',
    base_price_range: '₹450/shift - ₹950/shift',
    popular_tasks: ['Elderly Daily Living Support', 'Post-Op Vital Monitoring', 'Mobility & Physical Exercise', 'Medication Reminders', 'Dementia Care Companionship'],
    urgency_available: true,
    image_url: 'https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'cat-7',
    slug: 'drivers',
    name: 'Verified Drivers & Chauffeurs',
    name_hi: 'प्रमाणित चालक (ड्राइवर)',
    icon: 'Car',
    description: 'Police-verified commercial & personal vehicle drivers for outstation trips, daily commute, night-duty relief, and airport transfers.',
    base_price_range: '₹349/trip - ₹799/day',
    popular_tasks: ['Outstation Round Trip', 'Daily City Chauffeur (8h)', 'Airport Drop & Pickup', 'Night Emergency Driver', 'Commercial Delivery Support'],
    urgency_available: true,
    image_url: 'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'cat-8',
    slug: 'gardeners',
    name: 'Gardeners & Landscapers',
    name_hi: 'माली व बागवानी विशेषज्ञ',
    icon: 'Trees',
    description: 'Eco-trained horticultural artisans for lawn pruning, terrace garden setup, organic composting, plant nourishment, and pest control.',
    base_price_range: '₹249 - ₹649',
    popular_tasks: ['Lawn Mowing & Hedge Trim', 'Terrace Garden Maintenance', 'Organic Pest Spray', 'Potting & Soil Reconditioning', 'Flowering Plant Care'],
    urgency_available: false,
    image_url: 'https://images.unsplash.com/photo-1592417817098-8f3d6eb22509?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'cat-9',
    slug: 'cleaners',
    name: 'Deep Cleaners & Sanitizers',
    name_hi: 'गहन सफाई व सैनिटाइजर',
    icon: 'Sparkles',
    description: 'Trained hygiene brigades for bathroom descaling, sofa/carpet shampooing, kitchen chimney degreasing, and full-home deep sanitization.',
    base_price_range: '₹399 - ₹1,899',
    popular_tasks: ['Intensive Bathroom Descaling', 'Sofa & Mattress Shampooing', 'Kitchen Chimney & Tile Degreasing', 'Full House Move-In Deep Clean', 'Balcony & Glass Scrubbing'],
    urgency_available: true,
    image_url: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'cat-10',
    slug: 'technicians',
    name: 'Appliance & AC Technicians',
    name_hi: 'उपकरण व एसी तकनीशियन',
    icon: 'Cpu',
    description: 'ITI-certified appliance mechanics for split/window AC servicing, refrigerator gas refill, washing machine repair, and microwave troubleshooting.',
    base_price_range: '₹299 - ₹899',
    popular_tasks: ['AC Foam Jet Deep Service', 'AC Gas Refill & Leak Fix', 'Washing Machine Drum & Motor Fix', 'Refrigerator Cooling Repair', 'RO Water Purifier Filter Change'],
    urgency_available: true,
    image_url: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=500&auto=format&fit=crop&q=80',
  },
];

export const SEED_WORKERS: Worker[] = [
  {
    id: 'wrk-1',
    user_id: 'usr-work-1',
    cooperative_id: 'coop-1',
    cooperative_name: 'Mumbai Shramik Sahakari Sanstha',
    full_name: 'Rameshwar Patil',
    skills: ['Certified Wireman', 'MCB Diagnostics', 'Industrial Inverter Setup', 'Home Automation', '3-Phase Power'],
    service_category_ids: ['cat-1', 'cat-10'],
    experience_years: 11,
    verification_status: 'verified',
    insurance_status: true,
    availability: 'online',
    rating: 4.95,
    total_ratings_count: 142,
    total_jobs_completed: 318,
    hourly_rate: 280,
    base_visit_fee: 150,
    location: {
      lat: 19.0760,
      lng: 72.8777,
      area: 'Dadar West',
      city: 'Mumbai',
    },
    police_verified: true,
    kyc_verified: true,
    bank_account_verified: true,
    bio: '11+ years of experience as an ITI-certified master electrician. Member of Mumbai Shramik Sahakari Sanstha since 2018. Committed to precision, zero safety compromises, and transparent fair billing.',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'wrk-2',
    user_id: 'usr-work-2',
    cooperative_id: 'coop-2',
    cooperative_name: 'Delhi Karigar Kalyan Shramik Union',
    full_name: 'Sunita Devi',
    skills: ['Elder Companion', 'Palliative Attendant', 'Medication Routine', 'Mobility Therapy', 'First Aid Certified'],
    service_category_ids: ['cat-6', 'cat-5'],
    experience_years: 8,
    verification_status: 'verified',
    insurance_status: true,
    availability: 'online',
    rating: 4.98,
    total_ratings_count: 189,
    total_jobs_completed: 412,
    hourly_rate: 320,
    base_visit_fee: 180,
    location: {
      lat: 28.6139,
      lng: 77.2090,
      area: 'Lajpat Nagar',
      city: 'New Delhi',
    },
    police_verified: true,
    kyc_verified: true,
    bank_account_verified: true,
    bio: 'Certified Healthcare Attendant with NSDC Level-4 credential. Warm, empathetic care for seniors with Parkinson, stroke recovery, and post-hospitalization rehabilitation.',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'wrk-3',
    user_id: 'usr-work-3',
    cooperative_id: 'coop-1',
    cooperative_name: 'Mumbai Shramik Sahakari Sanstha',
    full_name: 'Ganesh Shinde',
    skills: ['High Pressure Hydro Jetting', 'Concealed Pipe Leakage', 'RO System Repair', 'Geyser Installation', 'CPVC Jointing'],
    service_category_ids: ['cat-2'],
    experience_years: 9,
    verification_status: 'verified',
    insurance_status: true,
    availability: 'online',
    rating: 4.88,
    total_ratings_count: 98,
    total_jobs_completed: 245,
    hourly_rate: 250,
    base_visit_fee: 140,
    location: {
      lat: 19.1136,
      lng: 72.8697,
      area: 'Andheri East',
      city: 'Mumbai',
    },
    police_verified: true,
    kyc_verified: true,
    bank_account_verified: true,
    bio: 'Specialist in concealed wall leakages and emergency sewer blockages. All modern diagnostic equipment and ultrasonic pipe testers carried on-site.',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'wrk-4',
    user_id: 'usr-work-4',
    cooperative_id: 'coop-3',
    cooperative_name: 'Bengaluru Skilled Artisans Cooperative Society',
    full_name: 'Manjunath Reddy',
    skills: ['Hardwood Joinery', 'Hydraulic Hinges', 'Modular Kitchens', 'Antique Restoration', 'Custom Bookcases'],
    service_category_ids: ['cat-3'],
    experience_years: 14,
    verification_status: 'verified',
    insurance_status: true,
    availability: 'busy',
    rating: 4.92,
    total_ratings_count: 165,
    total_jobs_completed: 390,
    hourly_rate: 340,
    base_visit_fee: 200,
    location: {
      lat: 12.9716,
      lng: 77.5946,
      area: 'Indiranagar',
      city: 'Bengaluru',
    },
    police_verified: true,
    kyc_verified: true,
    bank_account_verified: true,
    bio: 'Master Craftsman in Teak and Sheesham woodwork. 14 years dedicated to fine carpentry and modular installations with zero defect tolerance.',
    avatar_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'wrk-5',
    user_id: 'usr-work-5',
    cooperative_id: 'coop-4',
    cooperative_name: 'Pune Nirman & Seva Sahakari Society',
    full_name: 'Pooja Kadam',
    skills: ['Industrial Deep Scrubbing', 'Hospital Grade Sanitization', 'Sofa Upholstery Extraction', 'Kitchen Chimney Restoration'],
    service_category_ids: ['cat-9'],
    experience_years: 6,
    verification_status: 'verified',
    insurance_status: true,
    availability: 'online',
    rating: 4.91,
    total_ratings_count: 114,
    total_jobs_completed: 280,
    hourly_rate: 260,
    base_visit_fee: 150,
    location: {
      lat: 18.5204,
      lng: 73.8567,
      area: 'Kothrud',
      city: 'Pune',
    },
    police_verified: true,
    kyc_verified: true,
    bank_account_verified: true,
    bio: 'Leader of the Pune Sahakari Women Clean Hygiene Brigade. Eco-friendly biodegradable agents and high-temp steam sterilizers used.',
    avatar_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'wrk-6',
    user_id: 'usr-work-6',
    cooperative_id: 'coop-2',
    cooperative_name: 'Delhi Karigar Kalyan Shramik Union',
    full_name: 'Mohammad Irfan',
    skills: ['Inverter Split AC Expert', 'Ductless Multi-zone', 'PCB Chip Repair', 'Compressor Overhaul', 'Ecofriendly Gas Recharging'],
    service_category_ids: ['cat-10', 'cat-1'],
    experience_years: 10,
    verification_status: 'verified',
    insurance_status: true,
    availability: 'online',
    rating: 4.87,
    total_ratings_count: 87,
    total_jobs_completed: 215,
    hourly_rate: 290,
    base_visit_fee: 160,
    location: {
      lat: 28.5355,
      lng: 77.2600,
      area: 'Okhla Phase 3',
      city: 'New Delhi',
    },
    police_verified: true,
    kyc_verified: true,
    bank_account_verified: true,
    bio: 'Certified Refrigeration & Air Conditioning mechanic with 10 years experience. Fast diagnostics and guaranteed 60-day cooperative warranty on repairs.',
    avatar_url: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'wrk-7',
    user_id: 'usr-work-7',
    cooperative_id: 'coop-1',
    cooperative_name: 'Mumbai Shramik Sahakari Sanstha',
    full_name: 'Subhash Yadav',
    skills: ['Commercial Heavy Duty', 'VIP Defensive Driving', 'Highway Navigation', 'Automatic & Manual Fleet'],
    service_category_ids: ['cat-7'],
    experience_years: 12,
    verification_status: 'verified',
    insurance_status: true,
    availability: 'online',
    rating: 4.96,
    total_ratings_count: 178,
    total_jobs_completed: 530,
    hourly_rate: 220,
    base_visit_fee: 150,
    location: {
      lat: 19.0178,
      lng: 72.8478,
      area: 'Worli',
      city: 'Mumbai',
    },
    police_verified: true,
    kyc_verified: true,
    bank_account_verified: true,
    bio: 'Professional driver with clean 12-year incident-free record. Proficient in city navigation, outstation travel, and luxury vehicles.',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'wrk-8',
    user_id: 'usr-work-8',
    cooperative_id: 'coop-3',
    cooperative_name: 'Bengaluru Skilled Artisans Cooperative Society',
    full_name: 'Anand Kumar',
    skills: ['Terrace Garden Setup', 'Lawn Landscaping', 'Soil Microbiology', 'Rare Bonsai Grafting', 'Drip Irrigation'],
    service_category_ids: ['cat-8'],
    experience_years: 7,
    verification_status: 'verified',
    insurance_status: true,
    availability: 'online',
    rating: 4.94,
    total_ratings_count: 92,
    total_jobs_completed: 180,
    hourly_rate: 240,
    base_visit_fee: 120,
    location: {
      lat: 12.9279,
      lng: 77.6271,
      area: 'Koramangala',
      city: 'Bengaluru',
    },
    police_verified: true,
    kyc_verified: true,
    bank_account_verified: true,
    bio: 'Graduate in Agricultural Horticulture. Passionate about reviving urban balcony biodiversity and organic vegetable patches.',
    avatar_url: 'https://images.unsplash.com/photo-1592417817098-8f3d6eb22513?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'wrk-9',
    user_id: 'usr-work-9',
    cooperative_id: 'coop-2',
    cooperative_name: 'Delhi Karigar Kalyan Shramik Union',
    full_name: 'Rajesh Sharma',
    skills: ['Solar Inverter Grid Setup', '3-Phase Industrial Wiring', 'Smart Home Automation', 'Generator Maintenance'],
    service_category_ids: ['cat-1', 'cat-10'],
    experience_years: 13,
    verification_status: 'verified',
    insurance_status: true,
    availability: 'online',
    rating: 4.93,
    total_ratings_count: 154,
    total_jobs_completed: 340,
    hourly_rate: 290,
    base_visit_fee: 160,
    location: {
      lat: 28.6304,
      lng: 77.2177,
      area: 'Connaught Place',
      city: 'New Delhi',
    },
    police_verified: true,
    kyc_verified: true,
    bank_account_verified: true,
    bio: 'Licensed Senior Electrical Wireman with Delhi Labour Board certification. Expert in modern distribution boards and solar sync.',
    avatar_url: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'wrk-10',
    user_id: 'usr-work-10',
    cooperative_id: 'coop-1',
    cooperative_name: 'Odisha Karigar Sahayog Mahasangha',
    full_name: 'Debashish Mohanty',
    skills: ['High Voltage Substation Fitting', 'LED Architectural Lighting', 'Concealed Wall Conduit', 'Short Circuit Isolation'],
    service_category_ids: ['cat-1'],
    experience_years: 9,
    verification_status: 'verified',
    insurance_status: true,
    availability: 'online',
    rating: 4.96,
    total_ratings_count: 118,
    total_jobs_completed: 275,
    hourly_rate: 260,
    base_visit_fee: 140,
    location: {
      lat: 20.2961,
      lng: 85.8245,
      area: 'Saheed Nagar',
      city: 'Bhubaneswar',
    },
    police_verified: true,
    kyc_verified: true,
    bank_account_verified: true,
    bio: 'ITI Bhubaneswar gold-medalist wireman. Trusted by over 250 housing societies for safe zero-defect electrical installations.',
    avatar_url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'wrk-11',
    user_id: 'usr-work-11',
    cooperative_id: 'coop-3',
    cooperative_name: 'Bengaluru Skilled Artisans Cooperative Society',
    full_name: 'Suresh Nambiar',
    skills: ['Hydrojet Sewer Unclogging', 'Commercial Sensor Taps', 'Overhead Tank Pressure Pumps', 'Rainwater Harvesting Plumbing'],
    service_category_ids: ['cat-2'],
    experience_years: 10,
    verification_status: 'verified',
    insurance_status: true,
    availability: 'online',
    rating: 4.89,
    total_ratings_count: 89,
    total_jobs_completed: 210,
    hourly_rate: 270,
    base_visit_fee: 150,
    location: {
      lat: 12.9352,
      lng: 77.6245,
      area: 'HSR Layout',
      city: 'Bengaluru',
    },
    police_verified: true,
    kyc_verified: true,
    bank_account_verified: true,
    bio: 'Precision plumber with advanced ultrasonic diagnostic tools for concealed leakage detection without damaging bathroom tiles.',
    avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'wrk-12',
    user_id: 'usr-work-12',
    cooperative_id: 'coop-1',
    cooperative_name: 'Odisha Karigar Sahayog Mahasangha',
    full_name: 'Manoj Barik',
    skills: ['CPVC & GI Pipe Jointing', 'Bathroom Sanitary Redesign', 'Water Tank Automatic Float Valves', 'Kitchen Waste Grinder Fix'],
    service_category_ids: ['cat-2'],
    experience_years: 8,
    verification_status: 'verified',
    insurance_status: true,
    availability: 'online',
    rating: 4.94,
    total_ratings_count: 105,
    total_jobs_completed: 230,
    hourly_rate: 230,
    base_visit_fee: 130,
    location: {
      lat: 20.3540,
      lng: 85.8189,
      area: 'Patia',
      city: 'Bhubaneswar',
    },
    police_verified: true,
    kyc_verified: true,
    bank_account_verified: true,
    bio: 'Certified sanitation technician with extensive experience in residential apartment plumbing and rapid emergency dispatch.',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'wrk-13',
    user_id: 'usr-work-13',
    cooperative_id: 'coop-2',
    cooperative_name: 'Delhi Karigar Kalyan Shramik Union',
    full_name: 'Harpreet Singh',
    skills: ['Teak & Sheesham Furniture', 'Modular Kitchen Carcass Fitting', 'Hydraulic Bed Lifts', 'PU & Melamine Wood Polish'],
    service_category_ids: ['cat-3'],
    experience_years: 15,
    verification_status: 'verified',
    insurance_status: true,
    availability: 'online',
    rating: 4.97,
    total_ratings_count: 210,
    total_jobs_completed: 480,
    hourly_rate: 350,
    base_visit_fee: 200,
    location: {
      lat: 28.6506,
      lng: 77.1265,
      area: 'Rajouri Garden',
      city: 'New Delhi',
    },
    police_verified: true,
    kyc_verified: true,
    bank_account_verified: true,
    bio: 'Third-generation wood craftsman. Specialized in custom modular wardrobes, silent soft-close hinges, and heirloom antique restoration.',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'wrk-14',
    user_id: 'usr-work-14',
    cooperative_id: 'coop-1',
    cooperative_name: 'Odisha Karigar Sahayog Mahasangha',
    full_name: 'Jagannath Sahoo',
    skills: ['Custom Wood Carving', 'Door Lock Precision Channelling', 'Plywood Partitioning', 'Sofa Frame Structuring'],
    service_category_ids: ['cat-3'],
    experience_years: 11,
    verification_status: 'verified',
    insurance_status: true,
    availability: 'online',
    rating: 4.91,
    total_ratings_count: 95,
    total_jobs_completed: 215,
    hourly_rate: 300,
    base_visit_fee: 150,
    location: {
      lat: 20.4625,
      lng: 85.8828,
      area: 'Cuttack Sadar',
      city: 'Cuttack',
    },
    police_verified: true,
    kyc_verified: true,
    bank_account_verified: true,
    bio: 'Heritage wood craftsman combining traditional Odishan temple joinery with modern minimalist home furniture crafting.',
    avatar_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'wrk-15',
    user_id: 'usr-work-15',
    cooperative_id: 'coop-4',
    cooperative_name: 'Pune Nirman & Seva Sahakari Society',
    full_name: 'Vikram Salunkhe',
    skills: ['Luxury Royal Emulsion', 'Waterproof Damp Proofing', 'Textured Accent Walls', 'Airless Paint Spray Gun'],
    service_category_ids: ['cat-4'],
    experience_years: 12,
    verification_status: 'verified',
    insurance_status: true,
    availability: 'online',
    rating: 4.95,
    total_ratings_count: 140,
    total_jobs_completed: 310,
    hourly_rate: 280,
    base_visit_fee: 150,
    location: {
      lat: 18.5314,
      lng: 73.8446,
      area: 'Shivajinagar',
      city: 'Pune',
    },
    police_verified: true,
    kyc_verified: true,
    bank_account_verified: true,
    bio: 'Guild Master in interior painting and structural waterproofing. Dust-free electric sanding machines for pristine mirror-like wall finishes.',
    avatar_url: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'wrk-16',
    user_id: 'usr-work-16',
    cooperative_id: 'coop-1',
    cooperative_name: 'Odisha Karigar Sahayog Mahasangha',
    full_name: 'Ranjan Behera',
    skills: ['Exterior Weather Defense Coating', 'Wall Putty Leveling', 'Enamel Wood & Grill Polish', 'Epoxy Flooring'],
    service_category_ids: ['cat-4'],
    experience_years: 9,
    verification_status: 'verified',
    insurance_status: true,
    availability: 'online',
    rating: 4.92,
    total_ratings_count: 86,
    total_jobs_completed: 195,
    hourly_rate: 250,
    base_visit_fee: 130,
    location: {
      lat: 20.3015,
      lng: 85.8390,
      area: 'Chandrasekharpur',
      city: 'Bhubaneswar',
    },
    police_verified: true,
    kyc_verified: true,
    bank_account_verified: true,
    bio: 'Professional wall coating specialist with certified expertise in moisture measurement and eco-friendly zero-VOC non-toxic paints.',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'wrk-17',
    user_id: 'usr-work-17',
    cooperative_id: 'coop-1',
    cooperative_name: 'Mumbai Shramik Sahakari Sanstha',
    full_name: 'Alok Mukherjee',
    skills: ['Stencils & Geometric Wall Murals', 'Wood Grain Metal Polish', 'Water Seepage Tile Sealing', 'Anti-fungal Bathroom Primer'],
    service_category_ids: ['cat-4'],
    experience_years: 10,
    verification_status: 'verified',
    insurance_status: true,
    availability: 'online',
    rating: 4.88,
    total_ratings_count: 74,
    total_jobs_completed: 160,
    hourly_rate: 270,
    base_visit_fee: 140,
    location: {
      lat: 19.0596,
      lng: 72.8295,
      area: 'Bandra West',
      city: 'Mumbai',
    },
    police_verified: true,
    kyc_verified: true,
    bank_account_verified: true,
    bio: 'Interior painting artist specializing in designer textured walls, stencil highlights, and durable damp proofing coats.',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'wrk-18',
    user_id: 'usr-work-18',
    cooperative_id: 'coop-2',
    cooperative_name: 'Delhi Karigar Kalyan Shramik Union',
    full_name: 'Meena Kumari',
    skills: ['Nutritious Homestyle Cooking', 'Diabetic & Low-Sodium Meal Prep', 'Kitchen Sanitization', 'Event Buffet Support'],
    service_category_ids: ['cat-5'],
    experience_years: 8,
    verification_status: 'verified',
    insurance_status: true,
    availability: 'online',
    rating: 4.98,
    total_ratings_count: 175,
    total_jobs_completed: 420,
    hourly_rate: 220,
    base_visit_fee: 100,
    location: {
      lat: 28.5800,
      lng: 77.2300,
      area: 'Defence Colony',
      city: 'New Delhi',
    },
    police_verified: true,
    kyc_verified: true,
    bank_account_verified: true,
    bio: 'FSSAI certified food safety & hygiene training. Expert cook specialized in clean, wholesome North Indian, Gujarati, and Jain meals.',
    avatar_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'wrk-19',
    user_id: 'usr-work-19',
    cooperative_id: 'coop-1',
    cooperative_name: 'Odisha Karigar Sahayog Mahasangha',
    full_name: 'Kamala Jena',
    skills: ['Traditional Odia & Bengali Cooking', 'Complete Kitchen Housekeeping', 'Spices & Pantry Organization', 'Child Nutritional Meal Routine'],
    service_category_ids: ['cat-5'],
    experience_years: 7,
    verification_status: 'verified',
    insurance_status: true,
    availability: 'online',
    rating: 4.96,
    total_ratings_count: 132,
    total_jobs_completed: 290,
    hourly_rate: 200,
    base_visit_fee: 100,
    location: {
      lat: 20.2700,
      lng: 85.8400,
      area: 'Nayapalli',
      city: 'Bhubaneswar',
    },
    police_verified: true,
    kyc_verified: true,
    bank_account_verified: true,
    bio: 'Trusted cooperative domestic cook known for punctuality, hygienic kitchen maintenance, and authentic wholesome home food.',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'wrk-20',
    user_id: 'usr-work-20',
    cooperative_id: 'coop-1',
    cooperative_name: 'Mumbai Shramik Sahakari Sanstha',
    full_name: 'Shobha Gaikwad',
    skills: ['Maharashtrian & South Indian Delicacies', 'Elder Diet Planning', 'Steam Sterilized Vessel Cleaning', 'Weekly Meal Prepping'],
    service_category_ids: ['cat-5'],
    experience_years: 11,
    verification_status: 'verified',
    insurance_status: true,
    availability: 'online',
    rating: 4.93,
    total_ratings_count: 160,
    total_jobs_completed: 370,
    hourly_rate: 240,
    base_visit_fee: 120,
    location: {
      lat: 19.0222,
      lng: 72.8561,
      area: 'Matunga',
      city: 'Mumbai',
    },
    police_verified: true,
    kyc_verified: true,
    bank_account_verified: true,
    bio: 'Senior member of the Mumbai Domestic Workers Cooperative Society. Dedicated to warm hospitality, spotless kitchens, and healthy family meals.',
    avatar_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'wrk-21',
    user_id: 'usr-work-21',
    cooperative_id: 'coop-3',
    cooperative_name: 'Bengaluru Skilled Artisans Cooperative Society',
    full_name: 'Mary Joseph',
    skills: ['Post-Op Vital Monitoring', 'Tracheostomy & Catheter Support', 'Dementia Emotional Companionship', 'Physiotherapy Mobility Drills'],
    service_category_ids: ['cat-6'],
    experience_years: 14,
    verification_status: 'verified',
    insurance_status: true,
    availability: 'online',
    rating: 4.99,
    total_ratings_count: 220,
    total_jobs_completed: 510,
    hourly_rate: 380,
    base_visit_fee: 200,
    location: {
      lat: 12.9784,
      lng: 77.6408,
      area: 'Domlur',
      city: 'Bengaluru',
    },
    police_verified: true,
    kyc_verified: true,
    bank_account_verified: true,
    bio: 'Red Cross certified nursing attendant with 14 years clinical hospice & home palliative care experience. Deep empathy and professional medical discipline.',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'wrk-22',
    user_id: 'usr-work-22',
    cooperative_id: 'coop-1',
    cooperative_name: 'Odisha Karigar Sahayog Mahasangha',
    full_name: 'Basanti Nayak',
    skills: ['Senior Assisted Living Care', 'Blood Pressure & Sugar Monitoring', 'Bedridden Patient Hygiene', 'Medication Schedule Management'],
    service_category_ids: ['cat-6'],
    experience_years: 8,
    verification_status: 'verified',
    insurance_status: true,
    availability: 'online',
    rating: 4.95,
    total_ratings_count: 110,
    total_jobs_completed: 240,
    hourly_rate: 300,
    base_visit_fee: 150,
    location: {
      lat: 20.3150,
      lng: 85.8150,
      area: 'Jayadev Vihar',
      city: 'Bhubaneswar',
    },
    police_verified: true,
    kyc_verified: true,
    bank_account_verified: true,
    bio: 'Certified Healthcare Worker with NSDC validation. Gentle, patient, and trained in first-aid emergency response for senior citizens.',
    avatar_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'wrk-23',
    user_id: 'usr-work-23',
    cooperative_id: 'coop-2',
    cooperative_name: 'Delhi Karigar Kalyan Shramik Union',
    full_name: 'Gurpreet Gill',
    skills: ['Automatic & Manual Transmission', 'High-End Luxury SUV Pilot', 'National Highway Outstation Expert', 'Defensive Night Driving'],
    service_category_ids: ['cat-7'],
    experience_years: 13,
    verification_status: 'verified',
    insurance_status: true,
    availability: 'online',
    rating: 4.94,
    total_ratings_count: 165,
    total_jobs_completed: 490,
    hourly_rate: 250,
    base_visit_fee: 160,
    location: {
      lat: 28.5355,
      lng: 77.1550,
      area: 'Vasant Kunj',
      city: 'New Delhi',
    },
    police_verified: true,
    kyc_verified: true,
    bank_account_verified: true,
    bio: 'Professional corporate and family chauffeur. Zero traffic infractions, courteous demeanor, and master knowledge of all NCR and expressway routes.',
    avatar_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'wrk-24',
    user_id: 'usr-work-24',
    cooperative_id: 'coop-3',
    cooperative_name: 'Bengaluru Skilled Artisans Cooperative Society',
    full_name: 'K. Venkatesh',
    skills: ['Electric Vehicle (EV) Specialist', 'Airport Express Pilot', 'Corporate Daily Commute', 'Emergency Night Chauffeur'],
    service_category_ids: ['cat-7'],
    experience_years: 9,
    verification_status: 'verified',
    insurance_status: true,
    availability: 'online',
    rating: 4.91,
    total_ratings_count: 120,
    total_jobs_completed: 380,
    hourly_rate: 230,
    base_visit_fee: 140,
    location: {
      lat: 12.9856,
      lng: 77.7314,
      area: 'Whitefield',
      city: 'Bengaluru',
    },
    police_verified: true,
    kyc_verified: true,
    bank_account_verified: true,
    bio: 'Commercial badge certified driver with 9 years experience. Punctual, non-smoking, well-mannered, and certified in emergency vehicle mechanics.',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'wrk-25',
    user_id: 'usr-work-25',
    cooperative_id: 'coop-1',
    cooperative_name: 'Odisha Karigar Sahayog Mahasangha',
    full_name: 'Biranchi Narayan',
    skills: ['Terrace Urban Farming Setup', 'Ornamental Tree Pruning', 'Organic Vermicompost Soil Nutrition', 'Automatic Sprinkler System'],
    service_category_ids: ['cat-8'],
    experience_years: 12,
    verification_status: 'verified',
    insurance_status: true,
    availability: 'online',
    rating: 4.97,
    total_ratings_count: 145,
    total_jobs_completed: 310,
    hourly_rate: 250,
    base_visit_fee: 130,
    location: {
      lat: 20.3200,
      lng: 85.8050,
      area: 'Khandagiri',
      city: 'Bhubaneswar',
    },
    police_verified: true,
    kyc_verified: true,
    bank_account_verified: true,
    bio: 'Master horticulturist with a passion for designing lush, self-sustaining green balcony gardens, bonsai trees, and organic vegetable patches.',
    avatar_url: 'https://images.unsplash.com/photo-1592417817098-8f3d6eb22509?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'wrk-26',
    user_id: 'usr-work-26',
    cooperative_id: 'coop-4',
    cooperative_name: 'Pune Nirman & Seva Sahakari Society',
    full_name: 'Sanjay Mali',
    skills: ['Lawn Aeration & Turf Mowing', 'Vertical Green Wall Installation', 'Exotic Flowering Plants Care', 'Eco-friendly Neem Pest Shield'],
    service_category_ids: ['cat-8'],
    experience_years: 10,
    verification_status: 'verified',
    insurance_status: true,
    availability: 'online',
    rating: 4.93,
    total_ratings_count: 98,
    total_jobs_completed: 210,
    hourly_rate: 230,
    base_visit_fee: 120,
    location: {
      lat: 18.5679,
      lng: 73.9143,
      area: 'Viman Nagar',
      city: 'Pune',
    },
    police_verified: true,
    kyc_verified: true,
    bank_account_verified: true,
    bio: 'Dedicated landscaping artisan transforming residential societies and villas with evergreen plants, trimmed hedges, and vibrant flower beds.',
    avatar_url: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'wrk-27',
    user_id: 'usr-work-27',
    cooperative_id: 'coop-1',
    cooperative_name: 'Mumbai Shramik Sahakari Sanstha',
    full_name: 'Amit Das',
    skills: ['Intensive Bathroom Scale Descaling', 'Sofa Foam Injection Extraction', 'Kitchen Chimney Heavy Degreasing', 'Floor High-Speed Buffing'],
    service_category_ids: ['cat-9'],
    experience_years: 8,
    verification_status: 'verified',
    insurance_status: true,
    availability: 'online',
    rating: 4.90,
    total_ratings_count: 112,
    total_jobs_completed: 260,
    hourly_rate: 250,
    base_visit_fee: 140,
    location: {
      lat: 19.1363,
      lng: 72.8277,
      area: 'Lokhandwala',
      city: 'Mumbai',
    },
    police_verified: true,
    kyc_verified: true,
    bank_account_verified: true,
    bio: 'Equipped with heavy-duty industrial vacuum cleaners, single-disc floor scrubbers, and hospital-grade sanitizers for 100% germ-free homes.',
    avatar_url: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'wrk-28',
    user_id: 'usr-work-28',
    cooperative_id: 'coop-1',
    cooperative_name: 'Odisha Karigar Sahayog Mahasangha',
    full_name: 'Smita Rath',
    skills: ['Full Home Move-in Sanitization', 'Balcony & Window Track Cleaning', 'Mattress Anti-Allergen UV Treatment', 'Tile Grout Whitening'],
    service_category_ids: ['cat-9'],
    experience_years: 7,
    verification_status: 'verified',
    insurance_status: true,
    availability: 'online',
    rating: 4.95,
    total_ratings_count: 88,
    total_jobs_completed: 190,
    hourly_rate: 240,
    base_visit_fee: 130,
    location: {
      lat: 20.3300,
      lng: 85.8200,
      area: 'Infocity',
      city: 'Bhubaneswar',
    },
    police_verified: true,
    kyc_verified: true,
    bank_account_verified: true,
    bio: 'Trained leader of the Bhubaneswar Women Hygiene Guild. Meticulous eye for detail, safe non-corrosive chemical solutions, and sparkling results.',
    avatar_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'wrk-29',
    user_id: 'usr-work-29',
    cooperative_id: 'coop-1',
    cooperative_name: 'Odisha Karigar Sahayog Mahasangha',
    full_name: 'Santosh Pradhan',
    skills: ['Inverter AC Jet Pump Servicing', 'Washing Machine Drum & Sensor Board', 'Frost-Free Refrigerator Inverter PCB', 'Microwave Magnetron Repair'],
    service_category_ids: ['cat-10'],
    experience_years: 11,
    verification_status: 'verified',
    insurance_status: true,
    availability: 'online',
    rating: 4.94,
    total_ratings_count: 135,
    total_jobs_completed: 310,
    hourly_rate: 280,
    base_visit_fee: 150,
    location: {
      lat: 20.2500,
      lng: 85.8300,
      area: 'Old Town',
      city: 'Bhubaneswar',
    },
    police_verified: true,
    kyc_verified: true,
    bank_account_verified: true,
    bio: 'ITI-certified Master Technician with 11+ years experience in multi-brand electronics, inverter refrigeration, and washing machines.',
    avatar_url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'wrk-30',
    user_id: 'usr-work-30',
    cooperative_id: 'coop-1',
    cooperative_name: 'Mumbai Shramik Sahakari Sanstha',
    full_name: 'Prashant Kamble',
    skills: ['Split & Cassette AC Installation', 'Refrigerator Compressor Replacement', 'RO Filter Membrane Overhaul', 'Geyser Heating Element Setup'],
    service_category_ids: ['cat-10'],
    experience_years: 12,
    verification_status: 'verified',
    insurance_status: true,
    availability: 'online',
    rating: 4.92,
    total_ratings_count: 148,
    total_jobs_completed: 360,
    hourly_rate: 290,
    base_visit_fee: 160,
    location: {
      lat: 19.1663,
      lng: 72.8526,
      area: 'Goregaon East',
      city: 'Mumbai',
    },
    police_verified: true,
    kyc_verified: true,
    bank_account_verified: true,
    bio: 'Certified HVAC & Domestic Appliance Mechanic with genuine spare parts procurement and cooperative 60-day replacement warranty on all repairs.',
    avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300&auto=format&fit=crop&q=80',
  },
];

export const SEED_CERTIFICATIONS: WorkerCertification[] = [
  {
    id: 'cert-1',
    worker_id: 'wrk-1',
    certificate_name: 'National Skill Qualification Framework (NSQF) Level-5 Electrician',
    issuing_body: 'National Skill Development Corporation (NSDC) & Ministry of Skill Development',
    file_url: 'https://images.unsplash.com/photo-1589330694653-ded6df03f754?w=600&auto=format&fit=crop&q=80',
    verified: true,
    issue_date: '2021-04-15',
    expiry_date: '2031-04-14',
  },
  {
    id: 'cert-2',
    worker_id: 'wrk-1',
    certificate_name: 'Maharashtra PWD Class-A Electrical Wireman License',
    issuing_body: 'Licensing Board, Industries, Energy and Labour Dept, Govt of Maharashtra',
    file_url: 'https://images.unsplash.com/photo-1589330694653-ded6df03f754?w=600&auto=format&fit=crop&q=80',
    verified: true,
    issue_date: '2019-06-10',
    expiry_date: '2029-06-09',
  },
  {
    id: 'cert-3',
    worker_id: 'wrk-2',
    certificate_name: 'Geriatric Attendant & CPR First-Aid Certified Provider',
    issuing_body: 'Healthcare Sector Skill Council (HSSC)',
    file_url: 'https://images.unsplash.com/photo-1589330694653-ded6df03f754?w=600&auto=format&fit=crop&q=80',
    verified: true,
    issue_date: '2022-02-18',
    expiry_date: '2027-02-17',
  },
  {
    id: 'cert-4',
    worker_id: 'wrk-3',
    certificate_name: 'Master Plumber Certification (Plumbing Skill Council)',
    issuing_body: 'Indian Plumbing Skills Council (IPSC)',
    file_url: 'https://images.unsplash.com/photo-1589330694653-ded6df03f754?w=600&auto=format&fit=crop&q=80',
    verified: true,
    issue_date: '2020-08-01',
    expiry_date: '2030-07-31',
  },
];

export const SEED_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    user_id: 'usr-cust-1',
    full_name: 'Saumyadeep Sutradhar',
    contact: '+91 98201 45678',
    addresses: [
      {
        id: 'addr-1',
        label: 'Home (Bandra West)',
        address_line: 'Flat 402, Sea Crest Apartments, Perry Cross Road, Bandra West',
        city: 'Mumbai',
        pincode: '400050',
        lat: 19.0596,
        lng: 72.8295,
      },
      {
        id: 'addr-2',
        label: 'Parents House (Dadar)',
        address_line: '12 Shivaji Park, Keluskar Road, Dadar West',
        city: 'Mumbai',
        pincode: '400028',
        lat: 19.0280,
        lng: 72.8385,
      },
    ],
    is_institution: false,
  },
];

export const SEED_BOOKINGS: Booking[] = [
  {
    id: 'bk-101',
    booking_code: 'SHY-2026-9041',
    customer_id: 'cust-1',
    customer_name: 'Saumyadeep Sutradhar',
    customer_contact: '+91 98201 45678',
    worker_id: 'wrk-1',
    worker_name: 'Rameshwar Patil',
    worker_contact: '+91 98199 87654',
    worker_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    cooperative_name: 'Mumbai Shramik Sahakari Sanstha',
    service_category_id: 'cat-1',
    service_category_name: 'Electricians & Wiring',
    service_task: 'Inverter / UPS Backup Setup and MCB Diagnostics',
    description: 'Frequent tripping in master bedroom and need to connect 1.5 kVA inverter correctly to load circuit.',
    status: 'in_progress',
    scheduled_time: '2026-08-26T10:30:00+05:30',
    is_emergency: false,
    location: {
      address: 'Flat 402, Sea Crest Apartments, Perry Cross Road, Bandra West, Mumbai 400050',
      lat: 19.0596,
      lng: 72.8295,
    },
    price_breakdown: {
      worker_wage: 650,
      welfare_contribution: 50,
      coop_admin_fee: 40,
      platform_fee: 0,
      tax_amount: 0,
      emergency_fee: 0,
      total_amount: 740,
    },
    notes: 'Worker carrying calibrated multimeters and insulated screwdrivers. Identity badge verified.',
    created_at: '2026-08-25T18:30:00Z',
  },
  {
    id: 'bk-102',
    booking_code: 'SHY-2026-8812',
    customer_id: 'cust-1',
    customer_name: 'Saumyadeep Sutradhar',
    customer_contact: '+91 98201 45678',
    worker_id: 'wrk-3',
    worker_name: 'Ganesh Shinde',
    worker_contact: '+91 98223 99881',
    worker_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    cooperative_name: 'Mumbai Shramik Sahakari Sanstha',
    service_category_id: 'cat-2',
    service_category_name: 'Plumbers & Sanitation',
    service_task: 'Emergency Bathroom Pipe Leakage & Tap Seal',
    description: 'Under-sink hot water pipe leaking rapidly into cabinet.',
    status: 'completed',
    scheduled_time: '2026-08-20T14:00:00+05:30',
    is_emergency: true,
    location: {
      address: 'Flat 402, Sea Crest Apartments, Perry Cross Road, Bandra West, Mumbai 400050',
      lat: 19.0596,
      lng: 72.8295,
    },
    price_breakdown: {
      worker_wage: 520,
      welfare_contribution: 45,
      coop_admin_fee: 35,
      platform_fee: 0,
      tax_amount: 0,
      emergency_fee: 100,
      total_amount: 700,
    },
    notes: 'Urgent leak addressed in 25 minutes. New brass connector fitted.',
    created_at: '2026-08-20T13:10:00Z',
  },
];

export const SEED_INVOICES: PaymentInvoice[] = [
  {
    id: 'inv-101',
    booking_id: 'bk-102',
    booking_code: 'SHY-2026-8812',
    customer_name: 'Saumyadeep Sutradhar',
    worker_name: 'Ganesh Shinde',
    cooperative_name: 'Mumbai Shramik Sahakari Sanstha',
    amount: 700,
    payment_status: 'completed',
    payment_method: 'UPI',
    gateway_reference: 'UPI/MUM/20260820/9982410',
    invoice_number: 'COOP-INV-2026-08812',
    created_at: '2026-08-20T14:45:00Z',
  },
];

export const SEED_RATINGS: RatingReview[] = [
  {
    id: 'rev-1',
    booking_id: 'bk-102',
    rated_by: 'usr-cust-1',
    rated_by_name: 'Saumyadeep Sutradhar',
    rated_user_id: 'usr-work-3',
    rating: 5,
    comment: 'Exceptional service! Ganesh arrived within 20 mins during an emergency leak. Fixed it cleanly with authentic parts and explained the fair cooperative cost breakdown.',
    tags: ['Punctual', 'Expert Work', 'Fair Transparent Pricing', 'Cooperative Pride'],
    created_at: '2026-08-20T15:30:00Z',
  },
  {
    id: 'rev-2',
    booking_id: 'bk-100',
    rated_by: 'usr-cust-2',
    rated_by_name: 'Rajesh Nair',
    rated_user_id: 'usr-work-1',
    rating: 5,
    comment: 'Rameshwar is a master electrician. Rewired our complete living room switchboard and tested all surge protectors. Knowing 100% of my money goes to him and the welfare fund makes me proud to choose SAHYOG over corporate apps.',
    tags: ['Master Craft', 'Safety First', 'Respectful'],
    created_at: '2026-08-18T16:00:00Z',
  },
];

export const SEED_WELFARE: WorkerWelfare[] = [
  {
    id: 'welf-1',
    worker_id: 'wrk-1',
    worker_name: 'Rameshwar Patil',
    insurance_provider: 'Ayushman Bharat PM-JAY & United India Group Accidental Shield',
    policy_number: 'AB-PMJAY-MH-8842109',
    coverage_amount: 500000,
    expiry_date: '2027-03-31',
    welfare_fund_contribution: 14850,
    cooperative_dividend_earned: 4200,
    emergency_claim_status: 'none',
  },
  {
    id: 'welf-2',
    worker_id: 'wrk-2',
    worker_name: 'Sunita Devi',
    insurance_provider: 'National Health Insurance Guild + Delhi Cooperative Mutual Cover',
    policy_number: 'DL-COOP-HEALTH-3199',
    coverage_amount: 500000,
    expiry_date: '2027-04-30',
    welfare_fund_contribution: 18400,
    cooperative_dividend_earned: 5600,
    emergency_claim_status: 'none',
  },
];

export const SEED_GRIEVANCES: Grievance[] = [
  {
    id: 'grv-1',
    ticket_number: 'GRV-2026-0042',
    filed_by_role: 'worker',
    filed_by_id: 'usr-work-1',
    filed_by_name: 'Rameshwar Patil',
    category: 'welfare_delay',
    description: 'Annual tool maintenance subsidy of ₹2,500 pending verification by zone auditor.',
    status: 'under_review',
    resolution_notes: 'Federation Admin verified tool receipt. Payout scheduled for upcoming Friday ledger batch.',
    assigned_admin_name: 'Balwant Singh Deshmukh',
    created_at: '2026-08-22T10:00:00Z',
  },
  {
    id: 'grv-2',
    ticket_number: 'GRV-2026-0039',
    filed_by_role: 'customer',
    filed_by_id: 'usr-cust-1',
    filed_by_name: 'Saumyadeep Sutradhar',
    category: 'quality_of_work',
    description: 'Minor clarification on sealant drying time for bathroom tile joint.',
    status: 'resolved',
    resolution_notes: 'Worker called customer and provided 24-hr curing instructions. Resolved satisfactorily.',
    assigned_admin_name: 'Balwant Singh Deshmukh',
    created_at: '2026-08-21T09:00:00Z',
  },
];

export const SEED_DEMAND_FORECASTS: DemandForecast[] = [
  {
    id: 'df-1',
    region: 'Mumbai Western Suburbs (Bandra - Andheri)',
    city: 'Mumbai',
    service_category_id: 'cat-1',
    service_category_name: 'Electricians & Wiring',
    predicted_demand_units: 480,
    active_workers_available: 390,
    deficit_or_surplus: -90,
    period: 'Upcoming Week',
    confidence_score: 0.94,
    ai_recommendation: 'Predicted 23% spike due to monsoon load surges. Recommend activating 15 reserve apprentice wiremen from Thane society.',
    generated_at: '2026-08-25T06:00:00Z',
  },
  {
    id: 'df-2',
    region: 'Delhi NCR (South & Central)',
    city: 'New Delhi',
    service_category_id: 'cat-6',
    service_category_name: 'Elder & Patient Caregivers',
    predicted_demand_units: 320,
    active_workers_available: 345,
    deficit_or_surplus: 25,
    period: 'Next Month',
    confidence_score: 0.91,
    ai_recommendation: 'Adequate balance. Consider conducting specialized dementia companion refresher workshop for surplus pool.',
    generated_at: '2026-08-25T06:00:00Z',
  },
  {
    id: 'df-3',
    region: 'Bengaluru Tech Corridor (Koramangala - Whitefield)',
    city: 'Bengaluru',
    service_category_id: 'cat-9',
    service_category_name: 'Deep Cleaners & Sanitizers',
    predicted_demand_units: 610,
    active_workers_available: 480,
    deficit_or_surplus: -130,
    period: 'Upcoming Week',
    confidence_score: 0.96,
    ai_recommendation: 'High festive move-in demand. Reallocate 25 hygiene brigade teams from North Bengaluru cluster with temporary travel stipend.',
    generated_at: '2026-08-25T06:00:00Z',
  },
  {
    id: 'df-4',
    region: 'Pune Central & Kothrud',
    city: 'Pune',
    service_category_id: 'cat-10',
    service_category_name: 'Appliance & AC Technicians',
    predicted_demand_units: 290,
    active_workers_available: 285,
    deficit_or_surplus: -5,
    period: 'Seasonal Spike',
    confidence_score: 0.89,
    ai_recommendation: 'Stable capacity. Pre-book gas canister inventories with wholesale cooperative supplier.',
    generated_at: '2026-08-25T06:00:00Z',
  },
];

export const SEED_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    user_id: 'usr-cust-1',
    title: 'Artisan En Route',
    message: 'Rameshwar Patil (Mumbai Shramik Sahakari) is en route to your Bandra address. Estimated arrival: 10:25 AM.',
    type: 'booking',
    read_status: false,
    created_at: '2026-08-26T00:50:00Z',
  },
  {
    id: 'notif-2',
    user_id: 'usr-work-1',
    title: 'Welfare Dividend Credited',
    message: 'Cooperative annual surplus dividend of ₹4,200 has been credited to your welfare mutual fund account.',
    type: 'welfare',
    read_status: false,
    created_at: '2026-08-25T12:00:00Z',
  },
  {
    id: 'notif-3',
    user_id: 'usr-admin-1',
    title: '3 New Member KYC Applications',
    message: 'Review pending trade certifications and police verifications for Dadar Zone plumbers.',
    type: 'verification',
    read_status: false,
    created_at: '2026-08-25T14:30:00Z',
  },
];
