import React, { createContext, useContext, useState, useEffect } from 'react';

export type LanguageCode = 'en' | 'hi' | 'or' | 'mr' | 'bn' | 'ta' | 'te';

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string, defaultText?: string) => string;
}

const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    app_title: 'SAHYOG',
    app_tagline: 'Cooperative-Owned Digital Service Marketplace',
    motto: 'Dignity of Labour • Fair Minimum Wages • 100% Worker Welfare',
    top_badge: 'Cooperative-Owned Public Utility',
    top_cuts: '0% Aggregator Cuts — 100% Floor Wage to Artisans',
    top_welfare: 'Ayushman Bharat & ₹5 Lakh Accidental Cover',
    nav_home: 'Home',
    nav_services: 'Services & Trades',
    nav_care: 'Customer Care',
    nav_emergency: 'SOS Urgent',
    nav_dashboard: 'Dashboard',
    nav_my_bookings: 'My Bookings',
    nav_artisan_portal: 'Artisan Portal',
    nav_federation_admin: 'Admin Dashboard',
    nav_super_admin: 'Super Admin',
    nav_auth: 'Log In / Register',
    role_customer: 'Customer',
    role_worker: 'Artisan / Worker',
    role_admin: 'Federation Admin',
    role_super: 'Super Admin',
    hero_badge: 'Democratically Owned by Labour Cooperative Federations',
    hero_headline: 'Skilled Labour Services, Owned by Artisans Themselves.',
    hero_subtext: 'No 30% private aggregator cuts. 100% of fair floor wages go directly to certified electricians, plumbers, carpenters, caregivers, and technicians with collective accident insurance and mutual aid funds.',
    btn_book_artisan: 'Book Verified Artisan',
    btn_urgent_sos: 'Emergency SOS Dispatch',
    btn_view_all_trades: 'View All Trades',
    trust_nsdc: 'NSDC / ITI Certified',
    trust_police: 'Police Verified',
    trust_ayushman: 'Ayushman Health Shield',
    stats_verified_artisans: 'Verified Artisans',
    stats_fair_wages: 'Fair Wages Paid',
    stats_welfare_pool: 'Health & Welfare Pool',
    stats_cooperatives: 'Cooperatives',
    stats_sub_artisans: '100% KYC & Trade Certified',
    stats_sub_wages: '0% Aggregator Cuts',
    stats_sub_welfare: 'Universal Accident Shield',
    stats_sub_coop: 'Multi-State Network',
    why_title: 'Why Cooperative Ownership Changes Everything',
    why_badge: 'Ethical Paradigm Shift',
    why_subtext: 'Private tech aggregators commodify labour. SAHYOG is democratically owned by worker-members with legal governance, dividend rights, and social security.',
    corp_title: 'Corporate Gig Aggregators',
    corp_sub: 'Profit Extraction Model',
    corp_cut: '25-35% Cuts',
    corp_point1: 'Extracts up to 35% commission on every job from artisan earnings',
    corp_point2: 'Workers can be abruptly deactivated/banned by black-box algorithms',
    corp_point3: 'Zero health insurance, no provident fund, no accident protection',
    corp_point4: 'Predatory 300% surge pricing that gouges consumers without benefiting workers',
    coop_title: 'SAHYOG Cooperative Network',
    coop_sub: 'Worker-Owned & Community Governed',
    coop_cut: '0% Cuts',
    coop_point1: '100% fair floor wages paid directly to verified artisan members',
    coop_point2: 'Democratic dispute redressal — no automated algorithm account bans',
    coop_point3: 'Ayushman Bharat & ₹5 Lakh accidental cover standard for all active members',
    coop_point4: 'Annual surplus dividend distributed back to registered cooperative artisans',
    trades_badge: '10 Certified Trades',
    trades_title: 'Browse Cooperative Trades & Skills',
    trades_sub: 'Select a trade to inspect verified artisans, transparent rate cards, and schedule visits.',
    voices_badge: 'Voices of the Guild',
    voices_title: 'Dignity of Labour in Practice',
    voices_sub: 'Meet the skilled master artisans who power our homes and institutions every single day.',
    seal_title: 'Cooperative Seal of Trust',
    seal_sub: 'Multi-State Act Verified',
    seal_badge: '0% Commission Standard',
    floor_rate: 'Floor Rate',
    view_credentials: 'View Credentials',
    book_service: 'Book Service',
    book_artisan: 'Book Artisan',
    inst_badge: 'Institutional & Society Onboarding',
    inst_title: 'Need Contract Maintenance for Societies, Hospitals, or Campuses?',
    inst_sub: 'SAHYOG provides enterprise-grade verified workforce pools for facilities management, annual maintenance contracts (AMC), and residential housing societies with 100% statutory compliance.',
    inst_btn_rfp: 'Request Institutional RFP',
    inst_btn_audit: 'Schedule Facility Audit',
    search_placeholder: 'Search by trade, skill, locality (e.g. Electrician, Inverter, Leakage)...',
    filter_all: 'All Trades',
    active_in_progress: 'Active & In-Progress Bookings',
    no_active_bookings: 'No active bookings currently',
    live_progress: 'Live Job Progress',
    total_fair_fare: 'Total Fair Fare',
    invoice_btn: 'Invoice',
    dispute_btn: 'Dispute',
    advance_step_btn: 'Advance Step →',
    history_title: 'Service History & Downloadable Invoices',
    rate_review_btn: 'Rate & Review',
  },
  hi: {
    app_title: 'सहयोग',
    app_tagline: 'श्रमिक सहकारी स्वामित्व वाला डिजिटल सेवा मंच',
    motto: 'श्रम की गरिमा • उचित न्यूनतम मजदूरी • 100% श्रमिक कल्याण',
    top_badge: 'सहकारी स्वामित्व वाली लोकसेवा',
    top_cuts: '0% बिचौलिया कमीशन — 100% मजदूरी सीधे कारीगरों को',
    top_welfare: 'आयुष्मान भारत एवं ₹5 लाख दुर्घटना बीमा',
    nav_home: 'होम',
    nav_services: 'सेवाएं एवं ट्रेड्स',
    nav_care: 'ग्राहक सेवा',
    nav_emergency: 'आपातकालीन SOS',
    nav_dashboard: 'डैशबोर्ड',
    nav_my_bookings: 'मेरी बुकिंग्स',
    nav_artisan_portal: 'कारीगर पोर्टल',
    nav_federation_admin: 'प्रशासन डैशबोर्ड',
    nav_super_admin: 'सुपर एडमिन',
    nav_auth: 'साइन इन / साइन अप',
    role_customer: 'ग्राहक',
    role_worker: 'सहकारी कारीगर',
    role_admin: 'फेडरेशन एडमिन',
    role_super: 'सुपर एडमिन',
    hero_badge: 'श्रमिक सहकारी समितियों द्वारा लोकतांत्रिक रूप से संचालित',
    hero_headline: 'कुशल श्रम सेवाएं, स्वयं कारीगरों के स्वामित्व में।',
    hero_subtext: 'निजी एग्रीगेटर्स की कोई 30% कमीशन कटौती नहीं। 100% उचित न्यूनतम मजदूरी सीधे कारीगरों को।',
    btn_book_artisan: 'प्रमाणित कारीगर बुक करें',
    btn_urgent_sos: 'आपातकालीन SOS सेवा',
    btn_view_all_trades: 'सभी 10 ट्रेड्स देखें',
    trust_nsdc: 'NSDC / ITI प्रमाणित',
    trust_police: 'पुलिस सत्यापित',
    trust_ayushman: 'आयुष्मान स्वास्थ्य सुरक्षा',
    stats_verified_artisans: 'सत्यापित कारीगर',
    stats_fair_wages: 'कुल भुगतान',
    stats_welfare_pool: 'कल्याण व स्वास्थ्य कोष',
    stats_cooperatives: 'सहकारी समितियां',
    stats_sub_artisans: '100% KYC व ट्रेड प्रमाणित',
    stats_sub_wages: '0% बिचौलिया कटौती',
    stats_sub_welfare: 'सार्वभौमिक दुर्घटना सुरक्षा',
    stats_sub_coop: 'राष्ट्रीय सहकारी नेटवर्क',
    why_title: 'सहकारी स्वामित्व क्यों सब कुछ बदल देता है',
    why_badge: 'नैतिक बदलाव',
    why_subtext: 'निजी ऐप्स श्रमिकों का शोषण करते हैं। सहयोग कामगारों के स्वामित्व वाला लोकतांत्रिक मंच है।',
    corp_title: 'निजी गिग एग्रीगेटर्स',
    corp_sub: 'मुनाफाखोरी मॉडल',
    corp_cut: '25-35% कटौती',
    corp_point1: 'हर काम पर 35% तक का भारी कमीशन काटते हैं',
    corp_point2: 'एल्गोरिदम द्वारा कामगारों को बिना कारण ब्लॉक कर दिया जाता है',
    corp_point3: 'शून्य स्वास्थ्य बीमा, कोई दुर्घटना सुरक्षा नहीं',
    corp_point4: 'ग्राहकों से 300% सर्ज चार्ज की लूट',
    coop_title: 'सहयोग सहकारी नेटवर्क',
    coop_sub: 'कामगार स्वामित्व एवं पारदर्शी शासन',
    coop_cut: '0% कटौती',
    coop_point1: '100% उचित मजदूरी सीधे प्रमाणित कारीगरों को',
    coop_point2: 'लोकतांत्रिक शिकायत निवारण — कोई गुप्त बैन नहीं',
    coop_point3: 'आयुष्मान भारत एवं ₹5 लाख दुर्घटना सुरक्षा कवच',
    coop_point4: 'वार्षिक मुनाफे का लाभांश सीधे कामगारों में वितरित',
    trades_badge: '10 प्रमाणित ट्रेड्स',
    trades_title: 'सहकारी सेवाएं एवं कौशल खोजें',
    trades_sub: 'प्रमाणित कारीगर, पारदर्शी दरें और समय चुनें।',
    voices_badge: 'कारीगरों के अनुभव',
    voices_title: 'श्रम की गरिमा का प्रत्यक्ष प्रमाण',
    voices_sub: 'हमारे कुशल मास्टर कारीगरों से मिलें जो आपके घरों को संभालते हैं।',
    seal_title: 'सहकारी विश्वास की मुहर',
    seal_sub: 'मल्टी-स्टेट एक्ट प्रमाणित',
    seal_badge: '0% कमीशन मानक',
    floor_rate: 'न्यूनतम दर',
    view_credentials: 'प्रमाणपत्र देखें',
    book_service: 'सेवा बुक करें',
    book_artisan: 'कारीगर बुक करें',
    inst_badge: 'संस्थागत एवं सोसायटी अनुबंध',
    inst_title: 'सोसायटी या हॉस्पिटल के लिए रखरखाव अनुबंध चाहिए?',
    inst_sub: 'सहयोग हाउसिंग सोसायटियों और परिसरों के लिए संपूर्ण वैधानिक अनुपालन के साथ कुशल कार्यबल प्रदान करता है।',
    inst_btn_rfp: 'संस्थागत RFP भेजें',
    inst_btn_audit: 'निरीक्षण समय निर्धारित करें',
    search_placeholder: 'ट्रेड, कौशल या क्षेत्र खोजें (उदा. इलेक्ट्रीशियन, प्लंबर, वायरिंग)...',
    filter_all: 'सभी ट्रेड्स',
    active_in_progress: 'सक्रिय एवं प्रगति पर बुकिंग',
    no_active_bookings: 'वर्तमान में कोई सक्रिय बुकिंग नहीं',
    live_progress: 'कार्य की लाइव प्रगति',
    total_fair_fare: 'कुल उचित शुल्क',
    invoice_btn: 'रसीद',
    dispute_btn: 'शिकायत',
    advance_step_btn: 'अगला चरण →',
    history_title: 'सेवा इतिहास एवं इनवॉइस',
    rate_review_btn: 'रेटिंग एवं समीक्षा दें',
  },
  or: {
    app_title: 'ସହଯୋଗ',
    app_tagline: 'ଶ୍ରମିକ ସମବାୟ ମାଲିକାନା ଡିଜିଟାଲ ସେବା ବଜାର',
    motto: 'ଶ୍ରମର ମର୍ଯ୍ୟାଦା • ଉଚିତ ସର୍ବନିମ୍ନ ମଜୁରୀ • ୧୦୦% ଶ୍ରମିକ କଲ୍ୟାଣ',
    top_badge: 'ସମବାୟ ମାଲିକାନା ଲୋକ ସେବା ମଞ୍ଚ',
    top_cuts: '୦% ମଧ୍ୟସ୍ଥ କଟାଉତି — ୧୦୦% ନ୍ୟାଯ୍ୟ ମଜୁରୀ କାରିଗରଙ୍କୁ',
    top_welfare: 'ଆୟୁଷ୍ମାନ ଭାରତ ଓ ₹୫ ଲକ୍ଷ ଦୁର୍ଘଟଣା ସୁରକ୍ଷା',
    nav_home: 'ମୂଳପୃଷ୍ଠା',
    nav_services: 'ସେବା ଓ ବୃତ୍ତି',
    nav_care: 'ଗ୍ରାହକ ସେବା',
    nav_emergency: 'ଜରୁରୀ ସେବା (SOS)',
    nav_dashboard: 'ଡ୍ୟାସବୋର୍ଡ',
    nav_my_bookings: 'ମୋର ବୁକିଂ',
    nav_artisan_portal: 'କାରିଗର ପୋର୍ଟାଲ',
    nav_federation_admin: 'ଫେଡେରେସନ ପ୍ରଶାସନ',
    nav_super_admin: 'ମୁଖ୍ୟ ପ୍ରଶାସକ',
    nav_auth: 'ଲଗ୍-ଇନ୍ / ପଞ୍ଜୀକରଣ',
    role_customer: 'ଗ୍ରାହକ',
    role_worker: 'ସମବାୟ କାରିଗର',
    role_admin: 'ଫେଡେରେସନ ପ୍ରଶାସକ',
    role_super: 'ସୁପର ଆଡମିନ୍',
    hero_badge: 'ଶ୍ରମିକ ସମବାୟ ଫେଡେରେସନ ଦ୍ୱାରା ଗଣତାନ୍ତ୍ରିକ ଭାବେ ପରିଚାଳିତ',
    hero_headline: 'ଦକ୍ଷ ଶ୍ରମିକ ସେବା, ନିଜେ କାରିଗରମାନଙ୍କ ମାଲିକାନାରେ।',
    hero_subtext: 'କୌଣସି ୩୦% ଶୋଷଣକାରୀ କମିଶନ ନାହିଁ। ୧୦୦% ନ୍ୟାଯ୍ୟ ମଜୁରୀ ସିଧାସଳଖ ପ୍ରମାଣିତ ଇଲେକ୍ଟ୍ରିସିଆନ, ପ୍ଲମ୍ବର, ବଢ଼େଇ, ରୋଗୀ ସେବକ ଓ ଟେକ୍ନିସିଆନଙ୍କୁ ମିଳିଥାଏ, ସହିତ ଦୁର୍ଘଟଣା ବୀମା ଓ କଲ୍ୟାଣ ପାଣ୍ଠି ସୁବିଧା।',
    btn_book_artisan: 'ପ୍ରମାଣିତ କାରିଗର ବୁକ୍ କରନ୍ତୁ',
    btn_urgent_sos: 'ଜରୁରୀକାଳୀନ SOS ପ୍ରେରଣ',
    btn_view_all_trades: 'ସମସ୍ତ ସେବା ଦେଖନ୍ତୁ',
    trust_nsdc: 'NSDC / ITI ପ୍ରମାଣିତ',
    trust_police: 'ପୋଲିସ ଯାଞ୍ଚ ହୋଇଥିବା',
    trust_ayushman: 'ଆୟୁଷ୍ମାନ ସ୍ୱାସ୍ଥ୍ୟ କବଚ',
    stats_verified_artisans: 'ପ୍ରମାଣିତ କାରିଗର',
    stats_fair_wages: 'ବଣ୍ଟନ ହୋଇଥିବା ମଜୁରୀ',
    stats_welfare_pool: 'ସ୍ୱାସ୍ଥ୍ୟ ଓ କଲ୍ୟାଣ ପାଣ୍ଠି',
    stats_cooperatives: 'ସମବାୟ ସମିତି',
    stats_sub_artisans: '୧୦୦% KYC ଓ ପ୍ରମାଣପତ୍ର ଯାଞ୍ଚ',
    stats_sub_wages: '୦% ମଧ୍ୟସ୍ଥ କମିଶନ',
    stats_sub_welfare: 'ସାର୍ବଜନୀନ ଦୁର୍ଘଟଣା ବୀମା',
    stats_sub_coop: 'ବହୁ-ରାଜ୍ୟ ସମବାୟ ନେଟୱାର୍କ',
    why_title: 'ସମବାୟ ମାଲିକାନା କାହିଁକି ସବୁକିଛି ବଦଳାଇଦିଏ',
    why_badge: 'ନୈତିକ ବ୍ୟବସ୍ଥାର ପରିବର୍ତ୍ତନ',
    why_subtext: 'ଘରୋଇ ଗିଗ୍ କମ୍ପାନୀମାନେ ଶ୍ରମିକଙ୍କୁ ଶୋଷଣ କରନ୍ତି। ସହଯୋଗ ହେଉଛି ଶ୍ରମିକ-ସଦସ୍ୟଙ୍କ ମାଲିକାନା, ଗଣତାନ୍ତ୍ରିକ ନିୟନ୍ତ୍ରଣ ଏବଂ ସାମାଜିକ ସୁରକ୍ଷା ଯୁକ୍ତ ସମବାୟ।',
    corp_title: 'କର୍ପୋରେଟ୍ ଗିଗ୍ ଏଗ୍ରିଗେଟର',
    corp_sub: 'ମୁନାଫା ଖୋର ବ୍ୟବସ୍ଥା',
    corp_cut: '୨୫-୩୫% କଟାଉତି',
    corp_point1: 'କାରିଗରଙ୍କ ପ୍ରତ୍ୟେକ କାମରୁ ୩୫% ପର୍ଯ୍ୟନ୍ତ କମିଶନ କାଟିଥାନ୍ତି',
    corp_point2: 'ବିନା କୌଣସି କାରଣରେ ଆଲଗୋରିଦମ ଦ୍ୱାରା ଆଇଡି ବନ୍ଦ କରିଦିଅନ୍ତି',
    corp_point3: 'କୌଣସି ସ୍ୱାସ୍ଥ୍ୟ ବୀମା, ଭବିଷ୍ୟ ନିଧି ବା ଦୁର୍ଘଟଣା ସୁରକ୍ଷା ନାହିଁ',
    corp_point4: '୩୦୦% ପର୍ଯ୍ୟନ୍ତ ଅହେତୁକ ସର୍ଜ ମୂଲ୍ୟ ଯାହା ଗ୍ରାହକଙ୍କୁ ଶୋଷଣ କରେ',
    coop_title: 'ସହଯୋଗ ସମବାୟ ନେଟୱାର୍କ',
    coop_sub: 'ଶ୍ରମିକ ମାଲିକାନା ଓ ସମାଜ ନିୟନ୍ତ୍ରିତ',
    coop_cut: '୦% କଟାଉତି',
    coop_point1: '୧୦୦% ନ୍ୟାଯ୍ୟ ମଜୁରୀ ସିଧାସଳଖ ପ୍ରମାଣିତ ସଦସ୍ୟ କାରିଗରଙ୍କୁ ଦିଆଯାଏ',
    coop_point2: 'ଗଣତାନ୍ତ୍ରିକ ଅଭିଯୋଗ ସମାଧାନ — କୌଣସି ଆଲଗୋରିଦମ ବ୍ୟାନ ନାହିଁ',
    coop_point3: 'ଆୟୁଷ୍ମାନ ଭାରତ ଓ ₹୫ ଲକ୍ଷ ଦୁର୍ଘଟଣା ବୀମା ପ୍ରତ୍ୟେକ ସଦସ୍ୟଙ୍କ ପାଇଁ',
    coop_point4: 'ବାର୍ଷିକ ସମବାୟ ଲାଭାଂଶ ପଞ୍ଜୀକୃତ ଶ୍ରମିକଙ୍କ ମଧ୍ୟରେ ବଣ୍ଟନ',
    trades_badge: '୧୦ ପ୍ରମାଣିତ ବୃତ୍ତି',
    trades_title: 'ସମବାୟ କାରିଗର ସେବା ଅନ୍ୱେଷଣ କରନ୍ତୁ',
    trades_sub: 'ପ୍ରମାଣିତ କାରିଗର, ସ୍ୱଚ୍ଛ ଦର ତାଲିକା ଏବଂ ସମୟ ନିର୍ଦ୍ଧାରଣ କରିବା ପାଇଁ ବୃତ୍ତି ଚୟନ କରନ୍ତୁ।',
    voices_badge: 'କାରିଗରଙ୍କ ସ୍ୱର',
    voices_title: 'କାର୍ଯ୍ୟରେ ଶ୍ରମର ମର୍ଯ୍ୟାଦା',
    voices_sub: 'ଆମ ଘର ଓ ଅନୁଷ୍ଠାନକୁ ସଜାଡୁଥିବା ଦକ୍ଷ ମାଷ୍ଟର କାରିଗରମାନଙ୍କୁ ଭେଟନ୍ତୁ।',
    seal_title: 'ସମବାୟ ବିଶ୍ୱାସର ମୋହର',
    seal_sub: 'ବହୁ-ରାଜ୍ୟ ଆଇନ ଅନୁମୋଦିତ',
    seal_badge: '୦% କମିଶନ ମାନକ',
    floor_rate: 'ସର୍ବନିମ୍ନ ଦର',
    view_credentials: 'ପ୍ରମାଣପତ୍ର ଦେଖନ୍ତୁ',
    book_service: 'ସେବା ବୁକ୍ କରନ୍ତୁ',
    book_artisan: 'କାରିଗର ବୁକ୍ କରନ୍ତୁ',
    inst_badge: 'ଅନୁଷ୍ଠାନିକ ଓ ସୋସାଇଟି ଚୁକ୍ତି',
    inst_title: 'ସୋସାଇଟି, ହସ୍ପିଟାଲ ବା କ୍ୟାମ୍ପସ ପାଇଁ ଚୁକ୍ତିଭିତ୍ତିକ ରକ୍ଷଣାବେକ୍ଷଣ ଆବଶ୍ୟକ କି?',
    inst_sub: 'ସହଯୋଗ ସମ୍ପୂର୍ଣ୍ଣ ଆଇନଗତ ଅନୁପାଳନ ସହିତ ହାଉସିଂ ସୋସାଇଟି ଓ ଅନୁଷ୍ଠାନ ପାଇଁ ପ୍ରମାଣିତ କାରିଗର ଦଳ ଯୋଗାଇଥାଏ।',
    inst_btn_rfp: 'ଅନୁଷ୍ଠାନିକ RFP ଅନୁରୋଧ କରନ୍ତୁ',
    inst_btn_audit: 'ପରିଦର୍ଶନ ସମୟ ସ୍ଥିର କରନ୍ତୁ',
    search_placeholder: 'ବୃତ୍ତି, ଦକ୍ଷତା, ଅଞ୍ଚଳ ଖୋଜନ୍ତୁ (ଯଥା ଇଲେକ୍ଟ୍ରିସିଆନ, ପ୍ଲମ୍ବର, ଲିକେଜ୍)...',
    filter_all: 'ସମସ୍ତ ବୃତ୍ତି',
    active_in_progress: 'ଚାଲୁ ରହିଥିବା ବୁକିଂ',
    no_active_bookings: 'ବର୍ତ୍ତମାନ କୌଣସି ସକ୍ରିୟ ବୁକିଂ ନାହିଁ',
    live_progress: 'କାମର ଅଗ୍ରଗତି',
    total_fair_fare: 'ସମୁଦାୟ ନ୍ୟାଯ୍ୟ ମୂଲ୍ୟ',
    invoice_btn: 'ରସିଦ',
    dispute_btn: 'ଅଭିଯୋଗ',
    advance_step_btn: 'ପରବର୍ତ୍ତୀ ପଦକ୍ଷେପ →',
    history_title: 'ସେବା ଇତିହାସ ଓ ରସିଦ ଡାଉନଲୋଡ',
    rate_review_btn: 'ମୂଲ୍ୟାଙ୍କନ କରନ୍ତୁ',
  },
  mr: {
    app_title: 'सहयोग',
    app_tagline: 'कामगार सहकारी मालकीचे डिजिटल सेवा व्यासपीठ',
    motto: 'श्रमाची प्रतिष्ठा • रास्त किमान वेतन • 100% कामगार कल्याण',
    top_badge: 'सहकारी मालकीची लोकसेवा',
    top_cuts: '0% मध्यस्थ कमिशन — 100% वेतन थेट कारागिरांना',
    top_welfare: 'आयुष्मान भारत व ₹5 लाख अपघात विमा',
    nav_home: 'मुख्यपृष्ठ',
    nav_services: 'सेवा आणि कारागीर',
    nav_care: 'ग्राहक सेवा',
    nav_emergency: 'तातडीची मदत (SOS)',
    nav_dashboard: 'डॅशबोर्ड',
    nav_my_bookings: 'माझी बुकिंग्ज',
    nav_artisan_portal: 'कारागीर पोर्टल',
    nav_federation_admin: 'फेडरेशन प्रशासन',
    nav_super_admin: 'सुपर ॲडमिन',
    nav_auth: 'साइन इन / नोंदणी',
    role_customer: 'ग्राहक',
    role_worker: 'सहकारी कारागीर',
    role_admin: 'फेडरेशन प्रशासक',
    role_super: 'सुपर ॲडमिन',
    hero_badge: 'श्रमिक सहकारी संस्थांच्या मालकीचे',
    hero_headline: 'कुशल कारागीर सेवा, प्रत्यक्ष कामगारांच्या मालकीच्या!',
    hero_subtext: 'खाजगी कंपन्यांची कोणतीही लूट नाही. संपूर्ण रास्त मोबदला थेट कारागिरांना आणि पूर्ण आरोग्य व अपघात सुरक्षा.',
    btn_book_artisan: 'कारागीर निवडा',
    btn_urgent_sos: 'तातडीची SOS सेवा',
    btn_view_all_trades: 'सर्व सेवा पहा',
    trust_nsdc: 'NSDC / ITI प्रमाणित',
    trust_police: 'पोलीस पडताळणी झालेले',
    trust_ayushman: 'आयुष्मान स्वास्थ्य कवच',
    stats_verified_artisans: 'प्रमाणित कारागीर',
    stats_fair_wages: 'वाटप झालेले रास्त वेतन',
    stats_welfare_pool: 'आरोग्य व कल्याण निधी',
    stats_cooperatives: 'सहकारी सोसायट्या',
    stats_sub_artisans: '100% KYC व कौशल्य प्रमाणित',
    stats_sub_wages: '0% मध्यस्थ कपात',
    stats_sub_welfare: 'सर्वसमावेशक अपघात विमा',
    stats_sub_coop: 'बहु-राज्य सहकारी जाळे',
    why_title: 'सहकारी मालकी का श्रेष्ठ आहे?',
    why_badge: 'नैतिक बदल',
    why_subtext: 'खाजगी ॲप्स नफेखोरी करतात. सहयोग ही कामगारांच्या मालकीची लोककल्याणकारी संस्था आहे.',
    corp_title: 'खाजगी गिग कंपन्या',
    corp_sub: 'नफेखोरी मॉडेल',
    corp_cut: '25-35% कपात',
    corp_point1: 'प्रत्येक कामातून 35% पर्यंत कमिशन कापतात',
    corp_point2: 'अल्गोरिदमद्वारे अचानक खाते बंद केले जाते',
    corp_point3: 'कोणताही आरोग्य विमा किंवा सामाजिक सुरक्षा नाही',
    corp_point4: 'ग्राहकांना लुटणारी 300% सर्ज प्राईसिंग',
    coop_title: 'सहयोग सहकारी नेटवर्क',
    coop_sub: 'कामगार मालकी व पारदर्शक प्रशासन',
    coop_cut: '0% कपात',
    coop_point1: '100% रास्त मोबदला थेट प्रमाणित कारागिरांना',
    coop_point2: 'लोकशाही पद्धतीने तक्रार निवारण',
    coop_point3: 'आयुष्मान भारत व ₹5 लाख गट अपघात विमा',
    coop_point4: 'वार्षिक नफ्यातील लाभांश थेट कामगारांना',
    trades_badge: '10 प्रमाणित कौशल्ये',
    trades_title: 'सहकारी सेवा व कारागीर शोधा',
    trades_sub: 'प्रमाणित कारागीर, पारदर्शक दर आणि भेटीची वेळ निश्चित करा.',
    voices_badge: 'कारागिरांचे अनुभव',
    voices_title: 'कामाची प्रतिष्ठा आणि सन्मान',
    voices_sub: 'आमच्या कुशल मास्टर कारागिरांना भेटा जे तुमचे घर सुरळीत ठेवतात.',
    seal_title: 'सहकारी विश्वासाची मोहोर',
    seal_sub: 'मल्टी-स्टेट ॲक्ट प्रमाणित',
    seal_badge: '0% कमिशन मानक',
    floor_rate: 'किमान दर',
    view_credentials: 'प्रमाणपत्रे पहा',
    book_service: 'सेवा बुक करा',
    book_artisan: 'कारागीर बुक करा',
    inst_badge: 'संस्थात्मक व गृहनिर्माण करार',
    inst_title: 'सोसायटी किंवा हॉस्पिटलसाठी देखभाल करार हवा आहे का?',
    inst_sub: 'सहयोग संपूर्ण कायदेशीर नियमांनुसार कुशल मनुष्यबळ पुरवते.',
    inst_btn_rfp: 'संस्थात्मक RFP पाठवा',
    inst_btn_audit: 'तपासणी वेळ ठरवा',
    search_placeholder: 'सेवा किंवा कारागीर शोधा (उदा. वायरमन, प्लंबर, सुतार)...',
    filter_all: 'सर्व सेवा',
    active_in_progress: 'सक्रिय आणि चालू कामे',
    no_active_bookings: 'सध्या कोणतीही सक्रिय बुकिंग नाही',
    live_progress: 'कामाची थेट प्रगती',
    total_fair_fare: 'एकूण रास्त शुल्क',
    invoice_btn: 'पावती',
    dispute_btn: 'तक्रार',
    advance_step_btn: 'पुढील टप्पा →',
    history_title: 'मागील सेवेचा इतिहास व पावत्या',
    rate_review_btn: 'मूल्यांकन करा',
  },
  bn: {
    app_title: 'সহযোগ',
    app_tagline: 'শ্রমিক সমবায় মালিকানাধীন ডিজিটাল সেবা প্ল্যাটফর্ম',
    motto: 'श্রমের মর্যাদা • ন্যায্য মজুরি • শতভাগ কর্মী কল্যাণ',
    top_badge: 'সমবায় মালিকানাধীন জনসেবা প্ল্যাটফর্ম',
    top_cuts: '০% মধ্যস্বত্বভোগী কমিশন — ১০০% ন্যায্য মজুরি কারিগরের হাতে',
    top_welfare: 'আয়ুষ্মান ভারত ও ₹৫ লাখ দুর্ঘটনা বীমা',
    nav_home: 'হোম',
    nav_services: 'পরিষেবা ও ট্রেড',
    nav_emergency: 'জরুরি এসওএস (SOS)',
    nav_dashboard: 'ড্যাশবোর্ড',
    nav_my_bookings: 'আমার বুকিং',
    nav_artisan_portal: 'কারিগর পোর্টাল',
    nav_federation_admin: 'ফেডারেশন অ্যাডমিন',
    nav_super_admin: 'সুপার অ্যাডমিন',
    nav_auth: 'সাইন ইন / রেজিস্টার',
    role_customer: 'গ্রাহক',
    role_worker: 'সমবায় কারিগর',
    role_admin: 'ফেডারেশন প্রশাসক',
    role_super: 'সুপার অ্যাডমিন',
    hero_badge: 'শ্রমিক সমবায় ফেডারেশন দ্বারা গণতান্ত্রিকভাবে পরিচালিত',
    hero_headline: 'দক্ষ কারিগর পরিষেবা, সরাসরি শ্রমিকদের মালিকানাধীন।',
    hero_subtext: 'কোনো ৩০% শোষক কমিশন নেই। ১০০% ন্যায্য মজুরি সরাসরি সার্টিফাইড ইলেকট্রিশিয়ান, প্লাম্বার, ছুতার ও টেকনিশিয়ানদের কাছে পৌঁছায়।',
    btn_book_artisan: 'কারিগর বুক করুন',
    btn_urgent_sos: 'জরুরি এসওএস সেবা',
    btn_view_all_trades: 'সব ট্রেড দেখুন',
    trust_nsdc: 'NSDC / ITI প্রত্যয়িত',
    trust_police: 'পুলিশ ভেরিফাইড',
    trust_ayushman: 'আয়ুষ্মান স্বাস্থ্য সুরক্ষা',
    stats_verified_artisans: 'যাচাইকৃত কারিগর',
    stats_fair_wages: 'বিতরণকৃত ন্যায্য মজুরি',
    stats_welfare_pool: 'স্বাস্থ্য ও কল্যাণ তহবিল',
    stats_cooperatives: 'সমবায় সমিতি',
    stats_sub_artisans: '১০০% কেওয়াইসি ও ট্রেড প্রত্যয়িত',
    stats_sub_wages: '০% মধ্যস্থতাকারী কমিশন',
    stats_sub_welfare: 'সার্বজনীন দুর্ঘটনা বীমা',
    stats_sub_coop: 'বহু-রাজ্য সমবায় নেটওয়ার্ক',
    why_title: 'সমবায় মালিকানা কেন শ্রেষ্ঠ',
    why_badge: 'নৈতিক বিপ্লব',
    why_subtext: 'কর্পোরেট অ্যাপগুলো শ্রম শোষণ করে। সহযোগ শ্রমিক-সদস্যদের মালিকানাধীন একটি স্বচ্ছ সমবায়।',
    corp_title: 'কর্পোরেট গিগ অ্যাপ',
    corp_sub: 'মুনাফাখোর মডেল',
    corp_cut: '২৫-৩৫% কমিশন',
    corp_point1: 'কাজের থেকে ৩৫% পর্যন্ত কমিশন কেটে নেওয়া হয়',
    corp_point2: 'অ্যালগরিদমের মাধ্যমে হঠাৎ আইডি ব্লক করা হয়',
    corp_point3: 'কোনো স্বাস্থ্য বীমা বা দুর্ঘটনা সুরক্ষা নেই',
    corp_point4: '৩০০% সার্জ প্রাইসিং দিয়ে গ্রাহক শোষণ',
    coop_title: 'সহযোগ সমবায় নেটওয়ার্ক',
    coop_sub: 'শ্রমিক মালিকানাধীন ও সমাজ পরিচালিত',
    coop_cut: '০% কমিশন',
    coop_point1: '১০০% ন্যায্য মজুরি সরাসরি কারিগরের হাতে',
    coop_point2: 'গণতান্ত্রিক অভিযোগ নিষ্পত্তি ব্যবস্থা',
    coop_point3: 'আয়ুষ্মান ভারত ও ₹৫ লাখ দুর্ঘটনা কভার',
    coop_point4: 'বার্ষিক লভ্যাংশ সমবায় কর্মীদের মাঝে বণ্টন',
    trades_badge: '১০টি প্রত্যয়িত ট্রেড',
    trades_title: 'সমবায় ট্রেড ও পরিষেবা দেখুন',
    trades_sub: 'যাচাইকৃত কারিগর, স্বচ্ছ রেট কার্ড এবং সময়সূচী বেছে নিন।',
    voices_badge: 'কারিগরদের কণ্ঠস্বর',
    voices_title: 'শ্রমের মর্যাদা বাস্তবায়নে',
    voices_sub: 'আমাদের দক্ষ কারিগরদের সাথে পরিচিত হন যারা আপনার বাড়ি সচল রাখেন।',
    seal_title: 'সমবায় আস্থার প্রতীক',
    seal_sub: 'মাল্টি-স্টেট অ্যাক্ট অনুমোদিত',
    seal_badge: '০% কমিশন স্ট্যান্ডার্ড',
    floor_rate: 'ন্যূনতম দর',
    view_credentials: 'সনদ দেখুন',
    book_service: 'সেবা বুক করুন',
    book_artisan: 'কারিগর বুক করুন',
    inst_badge: 'প্রাতিষ্ঠানিক ও সোসাইটি চুক্তি',
    inst_title: 'সোসাইটি বা ক্যাম্পাসের জন্য রক্ষণাবেক্ষণ চুক্তি প্রয়োজন?',
    inst_sub: 'সহযোগ সম্পূর্ণ আইনি নিয়ম মেনে দক্ষ কর্মীদল সরবরাহ করে।',
    inst_btn_rfp: 'প্রাতিষ্ঠানিক RFP পাঠান',
    inst_btn_audit: 'পরিদর্শন নির্ধারণ করুন',
    search_placeholder: 'ট্রেড বা সেবা খুঁজুন (যেমন ইলেকট্রিশিয়ান, প্লাম্বার)...',
    filter_all: 'সকল ট্রেড',
    active_in_progress: 'চলমান বুকিং',
    no_active_bookings: 'বর্তমানে কোনো সক্রিয় বুকিং নেই',
    live_progress: 'কাজের অগ্রগতি',
    total_fair_fare: 'মোট ন্যায্য ভাড়া',
    invoice_btn: 'ইনভয়েস',
    dispute_btn: 'অভিযোগ',
    advance_step_btn: 'পরবর্তী ধাপ →',
    history_title: 'পূর্ববর্তী সেবার ইতিহাস ও চালান',
    rate_review_btn: 'রেটিং দিন',
  },
  ta: {
    app_title: 'சஹயோக்',
    app_tagline: 'தொழிலாளர் கூட்டுறவு உரிமையுள்ள சேவை தளம்',
    motto: 'உழைப்பின் கண்ணியம் • நியாயமான ஊதியம் • 100% தொழிலாளர் நலம்',
    top_badge: 'கூட்டுறவு சேவை தளம்',
    top_cuts: '0% இடைத்தரகர் கமிஷன் — 100% நியாய ஊதியம்',
    top_welfare: 'ஆயுஷ்மான் பாரத் & ₹5 லட்சம் விபத்து காப்பீடு',
    nav_home: 'முகப்பு',
    nav_services: 'சேவைகள் & தொழில்கள்',
    nav_emergency: 'அவசர உதவி (SOS)',
    nav_dashboard: 'டாஷ்போர்டு',
    nav_my_bookings: 'எனது முன்பதிவுகள்',
    nav_artisan_portal: 'தொழிலாளர் தளம்',
    nav_federation_admin: 'நிர்வாக பக்கம்',
    nav_super_admin: 'முதன்மை நிர்வாகி',
    nav_auth: 'உள்நுழைவு / பதிவு',
    role_customer: 'வாடிக்கையாளர்',
    role_worker: 'கூட்டுறவு தொழிலாளி',
    role_admin: 'கூட்டுறவு நிர்வாகி',
    role_super: 'முதன்மை நிர்வாகி',
    hero_badge: 'தொழிலாளர் கூட்டுறவு சங்கங்களின் கூட்டுடைமை',
    hero_headline: 'திறமையான தொழிலாளர் சேவைகள், தொழிலாளர்களின் கூட்டுடைமையில்!',
    hero_subtext: 'எந்தவொரு இடைத்தரகர் கமிஷனும் இல்லை. 100% நியாயமான ஊதியம் நேரடியாக தொழிலாளர்களுக்கு.',
    btn_book_artisan: 'சேவையை முன்பதிவு செய்',
    btn_urgent_sos: 'அவசர SOS உதவி',
    btn_view_all_trades: 'அனைத்து சேவைகள்',
    trust_nsdc: 'NSDC / ITI சான்றிதழ்',
    trust_police: 'காவல்துறை சரிபார்க்கப்பட்டது',
    trust_ayushman: 'ஆயுஷ்மான் காப்பீடு',
    stats_verified_artisans: 'சரிபார்க்கப்பட்ட தொழிலாளர்கள்',
    stats_fair_wages: 'வழங்கப்பட்ட நியாய ஊதியம்',
    stats_welfare_pool: 'நல நிதி தொகுப்பு',
    stats_cooperatives: 'கூட்டுறவு சங்கங்கள்',
    stats_sub_artisans: '100% KYC சரிபார்க்கப்பட்டது',
    stats_sub_wages: '0% தரகர் கமிஷன்',
    stats_sub_welfare: 'விபத்து காப்பீடு பாதுகாப்பு',
    stats_sub_coop: 'மாநில கூட்டுறவு வலையமைப்பு',
    why_title: 'கூட்டுறவு முறை ஏன் சிறந்தது?',
    why_badge: 'நெறிமுறை மாற்றம்',
    why_subtext: 'தனியார் நிறுவனங்கள் உழைப்பை சுரண்டுகின்றன. சஹயோக் தொழிலாளர்களின் கூட்டுடைமை இயக்கம்.',
    corp_title: 'தனியார் கிக் நிறுவனங்கள்',
    corp_sub: 'லாப நோக்கு முறை',
    corp_cut: '25-35% கமிஷன்',
    corp_point1: 'ஒவ்வொரு பணியிலும் 35% வரை கமிஷன் பிடிக்கப்படுகிறது',
    corp_point2: 'திடீரென கணக்குகள் முடக்கப்படும் நிலை',
    corp_point3: 'மருத்துவ காப்பீடு மற்றும் பாதுகாப்பு இல்லை',
    corp_point4: '300% கூடுதல் கட்டண உயர்வு',
    coop_title: 'சஹயோக் கூட்டுறவு வலையமைப்பு',
    coop_sub: 'தொழிலாளர் உரிமையுள்ள தளம்',
    coop_cut: '0% கமிஷன்',
    coop_point1: '100% நியாய ஊதியம் நேரடியாக தொழிலாளர்களுக்கு',
    coop_point2: 'ஜனநாயக ரீதியான குறைதீர்ப்பு முறை',
    coop_point3: 'ஆயுஷ்மான் பாரத் மற்றும் ₹5 லட்சம் விபத்து காப்பீடு',
    coop_point4: 'ஆண்டு கூட்டுறவு லாபப் பகிர்வு',
    trades_badge: '10 சான்றளிக்கப்பட்ட தொழில்கள்',
    trades_title: 'கூட்டுறவு சேவைகளை காண்க',
    trades_sub: 'சான்றளிக்கப்பட்ட தொழிலாளர்கள் மற்றும் வெளிப்படையான கட்டணங்களை அறியவும்.',
    voices_badge: 'தொழிலாளர்களின் குரல்',
    voices_title: 'உழைப்பின் கண்ணியம்',
    voices_sub: 'உங்கள் வீடுகளை பாதுகாக்கும் எங்கள் கைவினைஞர்களை சந்தியுங்கள்.',
    seal_title: 'கூட்டுறவு நம்பிக்கை முத்திரை',
    seal_sub: 'அங்கீகரிக்கப்பட்ட கூட்டுறவு',
    seal_badge: '0% கமிஷன் தரம்',
    floor_rate: 'குறைந்தபட்ச கட்டணம்',
    view_credentials: 'சான்றிதழ் பார்க்க',
    book_service: 'முன்பதிவு செய்',
    book_artisan: 'தொழிலாளரை முன்பதிவு செய்',
    inst_badge: 'நிறுவன ஒப்பந்தங்கள்',
    inst_title: 'அடுக்குமாடி குடியிருப்புகளுக்கு பராமரிப்பு தேவையா?',
    inst_sub: 'சஹயோக் சட்டப்பூர்வமாக அங்கீகரிக்கப்பட்ட தொழிலாளர்களை வழங்குகிறது.',
    inst_btn_rfp: 'RFP கோரிக்கை அனுப்பவும்',
    inst_btn_audit: 'பரிசோதனை நேரம் ஒதுக்குங்கள்',
    search_placeholder: 'தொழில் அல்லது சேவை தேடுங்கள்...',
    filter_all: 'அனைத்து தொழில்கள்',
    active_in_progress: 'செயலில் உள்ள முன்பதிவுகள்',
    no_active_bookings: 'தற்போது முன்பதிவுகள் இல்லை',
    live_progress: 'பணி முன்னேற்றம்',
    total_fair_fare: 'மொத்த கட்டணம்',
    invoice_btn: 'ரசீது',
    dispute_btn: 'புகார்',
    advance_step_btn: 'அடுத்த கட்டம் →',
    history_title: 'முந்தைய சேவைகள் மற்றும் ரசீதுகள்',
    rate_review_btn: 'மதிப்பீடு செய்க',
  },
  te: {
    app_title: 'సహయోగ్',
    app_tagline: 'కార్మిక సహకార యాజమాన్య డిజిటల్ సేవా వేదిక',
    motto: 'శ్రమ గౌరవం • న్యాయమైన వేతనం • 100% కార్మిక సంక్షేమం',
    top_badge: 'సహకార సేవా వేదిక',
    top_cuts: '0% మధ్యవర్తి కమీషన్ — 100% కనీస వేతనం',
    top_welfare: 'ఆయుష్మాన్ భారత్ & ₹5 లక్షల ప్రమాద బీమా',
    nav_home: 'హోమ్',
    nav_services: 'సేవలు & నైపుణ్యాలు',
    nav_emergency: 'అత్యవసర SOS సేవ',
    nav_dashboard: 'డాష్‌బోర్డ్',
    nav_my_bookings: 'నా బుకింగ్‌లు',
    nav_artisan_portal: 'కార్మిక పోర్టల్',
    nav_federation_admin: 'ఫెడరేషన్ అడ్మిన్',
    nav_super_admin: 'సూపర్ అడ్మిన్',
    nav_auth: 'సైన్ ఇన్ / రిజిస్టర్',
    role_customer: 'కస్టమర్',
    role_worker: 'సహకార కళాకారుడు',
    role_admin: 'ఫెడరేషన్ నిర్వాహకుడు',
    role_super: 'సూపర్ అడ్మిన్',
    hero_badge: 'కార్మిక సహకార సమాఖ్యల యాజమాన్యం',
    hero_headline: 'నైపుణ్యం కలిగిన కార్మిక సేవలు, కార్మికుల స్వంత భాగస్వామ్యంలో!',
    hero_subtext: 'ఎటువంటి 30% మధ్యవర్తుల దోపిడీ లేదు. 100% న్యాయమైన వేతనం నేరుగా ఎలక్ట్రీషియన్లు, ప్లంబర్లు, వడ్రంగులు మరియు టెక్నీషియన్లకు అందుతుంది.',
    btn_book_artisan: 'కళాకారుడిని బుక్ చేయండి',
    btn_urgent_sos: 'అత్యవసర SOS సర్వీస్',
    btn_view_all_trades: 'అన్ని సేవలు చూడండి',
    trust_nsdc: 'NSDC / ITI సర్టిఫైడ్',
    trust_police: 'పోలీస్ ధృవీకరణ పొందిన',
    trust_ayushman: 'ఆయుష్మాన్ ఆరోగ్య కవచం',
    stats_verified_artisans: 'ధృవీకరించబడిన కార్మికులు',
    stats_fair_wages: 'పంపిణీ చేసిన న్యాయ వేతనాలు',
    stats_welfare_pool: 'సంక్షేమ నిధి పూల్',
    stats_cooperatives: 'సహకార సంఘాలు',
    stats_sub_artisans: '100% KYC మరియు నైపుణ్య ధృవీకరణ',
    stats_sub_wages: '0% మధ్యవర్తి కమీషన్',
    stats_sub_welfare: 'సార్వత్రిక ప్రమాద బీమా',
    stats_sub_coop: 'బహుళ రాష్ట్రాల నెట్‌వర్క్',
    why_title: 'సహకార యాజమాన్యం ఎందుకు ఉత్తమం?',
    why_badge: 'నైతిక మార్పు',
    why_subtext: 'ప్రైవేట్ కంపెనీలు కార్మికులను దోపిడీ చేస్తాయి. సహయోగ్ కార్మిక-సభ్యుల యాజమాన్యంలోని సంస్థ.',
    corp_title: 'కార్పొరేట్ గిగ్ కంపెనీలు',
    corp_sub: 'లాభాపేక్ష నమూనా',
    corp_cut: '25-35% కోతలు',
    corp_point1: 'ప్రతి పని నుండి 35% వరకు కమీషన్ కట్ చేస్తారు',
    corp_point2: 'అల్గోరిథం ద్వారా అకస్మాత్తుగా ఖాతాలు నిలిపివేత',
    corp_point3: 'ఎటువంటి ఆరోగ్య బీమా లేదా భద్రత ఉండదు',
    corp_point4: 'వినియోగదారులను దోపిడీ చేసే 300% సర్జ్ ధరలు',
    coop_title: 'సహయోగ్ సహకార నెట్‌వర్క్',
    coop_sub: 'కార్మికుల యాజమాన్యం & పారదర్శకత',
    coop_cut: '0% కోతలు',
    coop_point1: '100% కనీస వేతనం నేరుగా కార్మికులకే',
    coop_point2: 'ప్రజాస్వామ్య పరిష్కార విధానం',
    coop_point3: 'ఆయుష్మాన్ భారత్ & ₹5 లక్షల ప్రమాద బీమా',
    coop_point4: 'వార్షిక సహకార డివిడెండ్ పంపిణీ',
    trades_badge: '10 ధృవీకరించబడిన వృత్తులు',
    trades_title: 'సహకార సేవలను అన్వేషించండి',
    trades_sub: 'ధృవీకరించబడిన కళాకారులు, పారదర్శక రేట్ కార్డులను చూడండి.',
    voices_badge: 'కార్మికుల గొంతుక',
    voices_title: 'శ్రమ గౌరవానికి నిదర్శనం',
    voices_sub: 'మా నైపుణ్యం కలిగిన కళాకారులను కలవండి.',
    seal_title: 'సహకార విశ్వాస ముద్ర',
    seal_sub: 'చట్టబద్ధంగా నమోదిత',
    seal_badge: '0% కమీషన్ ప్రమాణం',
    floor_rate: 'కనీస రేటు',
    view_credentials: 'సర్టిఫికెట్లు చూడండి',
    book_service: 'సేవను బుక్ చేయండి',
    book_artisan: 'ఆర్టిజాన్‌ను బుక్ చేయండి',
    inst_badge: 'సంస్థాగత ఒప్పందాలు',
    inst_title: 'సొసైటీలు లేదా క్యాంపస్‌లకు నిర్వహణ సేవలు కావాలా?',
    inst_sub: 'సహయోగ్ చట్టబద్ధమైన నైపుణ్య కార్మికులను అందిస్తుంది.',
    inst_btn_rfp: 'RFP అభ్యర్థన పంపండి',
    inst_btn_audit: 'ఆడిట్ షెడ్యూల్ చేయండి',
    search_placeholder: 'సేవను వెతకండి (ఉదా. ఎలక్ట్రీషియన్, ప్లంబర్)...',
    filter_all: 'అన్ని వృత్తులు',
    active_in_progress: 'ప్రస్తుతం నడుస్తున్న బుకింగ్‌లు',
    no_active_bookings: 'ప్రస్తుతం ఎటువంటి బుకింగ్‌లు లేవు',
    live_progress: 'పని పురోగతి',
    total_fair_fare: 'మొత్తం న్యాయమైన ఛార్జీ',
    invoice_btn: 'రసీదు',
    dispute_btn: 'ఫిర్యాదు',
    advance_step_btn: 'తదుపరి దశ →',
    history_title: 'గత సేవల రికార్డు మరియు రసీదులు',
    rate_review_btn: 'రేటింగ్ ఇవ్వండి',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    const saved = localStorage.getItem('sahyog_language');
    return (saved as LanguageCode) || 'en';
  });

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
    localStorage.setItem('sahyog_language', lang);
  };

  const t = (key: string, defaultText: string = ''): string => {
    if (TRANSLATIONS[language]?.[key]) {
      return TRANSLATIONS[language][key];
    }
    if (TRANSLATIONS.en?.[key]) {
      return TRANSLATIONS.en[key];
    }
    return defaultText || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
